// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nvnmchain/anchoring/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// RegistryNameMatchMode selects how QuerySearchRegistriesByNameRequest.name is
// matched against a registry's name. Matching is always case-insensitive.
type RegistryNameMatchMode int32

const (
	// Unspecified defaults to EXACT.
	RegistryNameMatchMode_REGISTRY_NAME_MATCH_MODE_UNSPECIFIED RegistryNameMatchMode = 0
	// Name must equal the query exactly (case-insensitive).
	RegistryNameMatchMode_REGISTRY_NAME_MATCH_MODE_EXACT RegistryNameMatchMode = 1
	// Name must start with the query.
	RegistryNameMatchMode_REGISTRY_NAME_MATCH_MODE_PREFIX RegistryNameMatchMode = 2
	// Name must end with the query.
	RegistryNameMatchMode_REGISTRY_NAME_MATCH_MODE_SUFFIX RegistryNameMatchMode = 3
	// Name must contain the query anywhere.
	RegistryNameMatchMode_REGISTRY_NAME_MATCH_MODE_CONTAINS RegistryNameMatchMode = 4
)

var RegistryNameMatchMode_name = map[int32]string{
	0: "REGISTRY_NAME_MATCH_MODE_UNSPECIFIED",
	1: "REGISTRY_NAME_MATCH_MODE_EXACT",
	2: "REGISTRY_NAME_MATCH_MODE_PREFIX",
	3: "REGISTRY_NAME_MATCH_MODE_SUFFIX",
	4: "REGISTRY_NAME_MATCH_MODE_CONTAINS",
}

var RegistryNameMatchMode_value = map[string]int32{
	"REGISTRY_NAME_MATCH_MODE_UNSPECIFIED": 0,
	"REGISTRY_NAME_MATCH_MODE_EXACT":       1,
	"REGISTRY_NAME_MATCH_MODE_PREFIX":      2,
	"REGISTRY_NAME_MATCH_MODE_SUFFIX":      3,
	"REGISTRY_NAME_MATCH_MODE_CONTAINS":    4,
}

func (x RegistryNameMatchMode) String() string {
	return proto.EnumName(RegistryNameMatchMode_name, int32(x))
}

func (RegistryNameMatchMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_85f0e510b882f047, []int{0}
}

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_85f0e510b882f047, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_85f0e510b882f047, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryRecordsRequest is request type for the Query/Records RPC method.
type QueryRecordsRequest struct {
	Checksum   string `protobuf:"bytes,1,opt,name=checksum,proto3" json:"checksum,omitempty"`
	RegistryId uint64 `protobuf:"varint,2,opt,name=registry_id,json=registryId,proto3" json:"registry_id,omitempty"`
	RecordId   uint64 `protobuf:"varint,3,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	Index      uint64 `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
	// pagination defines an optional pagination for the request.
	Pagination *query.PageRequest `protobuf:"bytes,5,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryRecordsRequest) Reset()         { *m = QueryRecordsRequest{} }
func (m *QueryRecordsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRecordsRequest) ProtoMessage()    {}
func (*QueryRecordsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_85f0e510b882f047, []int{2}
}
func (m *QueryRecordsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRecordsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRecordsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRecordsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRecordsRequest.Merge(m, src)
}
func (m *QueryRecordsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRecordsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRecordsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRecordsRequest proto.InternalMessageInfo

func (m *QueryRecordsRequest) GetChecksum() string {
	if m != nil {
		return m.Checksum
	}
	return ""
}

func (m *QueryRecordsRequest) GetRegistryId() uint64 {
	if m != nil {
		return m.RegistryId
	}
	return 0
}

func (m *QueryRecordsRequest) GetRecordId() uint64 {
	if m != nil {
		return m.RecordId
	}
	return 0
}

func (m *QueryRecordsRequest) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *QueryRecordsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryRecordsResponse is response type for the Query/Documents RPC method.
type QueryRecordsResponse struct {
	// records is a list of records
	Records []*Record `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	// pagination defines the pagination in the response.
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryRecordsResponse) Reset()         { *m = QueryRecordsResponse{} }
func (m *QueryRecordsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRecordsResponse) ProtoMessage()    {}
func (*QueryRecordsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_85f0e510b882f047, []int{3}
}
func (m *QueryRecordsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRecordsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRecordsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRecordsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRecordsResponse.Merge(m, src)
}
func (m *QueryRecordsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRecordsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRecordsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRecordsResponse proto.InternalMessageInfo

func (m *QueryRecordsResponse) GetRecords() []*Record {
	if m != nil {
		return m.Records
	}
	return nil
}

func (m *QueryRecordsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryRegistriesRequest is request type for the Query/Registries RPC method.
type QueryRegistriesRequest struct {
	// registry_id is an optional filter for a specific registry
	RegistryId uint64 `protobuf:"varint,1,opt,name=registry_id,json=registryId,proto3" json:"registry_id,omitempty"`
	// pagination defines an optional pagination for the request.
	Pagination *query.PageRequest `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryRegistriesRequest) Reset()         { *m = QueryRegistriesRequest{} }
func (m *QueryRegistriesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRegistriesRequest) ProtoMessage()    {}
func (*QueryRegistriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_85f0e510b882f047, []int{4}
}
func (m *QueryRegistriesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRegistriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRegistriesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRegistriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRegistriesRequest.Merge(m, src)
}
func (m *QueryRegistriesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRegistriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRegistriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRegistriesRequest proto.InternalMessageInfo

func (m *QueryRegistriesRequest) GetRegistryId() uint64 {
	if m != nil {
		return m.RegistryId
	}
	return 0
}

func (m *QueryRegistriesRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryRegistriesResponse is response type for the Query/Registries RPC method.
type QueryRegistriesResponse struct {
	// registries is a list of registries
	Registries []*Registry `protobuf:"bytes,1,rep,name=registries,proto3" json:"registries,omitempty"`
	// pagination defines the pagination in the response.
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryRegistriesResponse) Reset()         { *m = QueryRegistriesResponse{} }
func (m *QueryRegistriesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRegistriesResponse) ProtoMessage()    {}
func (*QueryRegistriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_85f0e510b882f047, []int{5}
}
func (m *QueryRegistriesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRegistriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRegistriesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRegistriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRegistriesResponse.Merge(m, src)
}
func (m *QueryRegistriesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRegistriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRegistriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRegistriesResponse proto.InternalMessageInfo

func (m *QueryRegistriesResponse) GetRegistries() []*Registry {
	if m != nil {
		return m.Registries
	}
	return nil
}

func (m *QueryRegistriesResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryRegistryRequest is request type for the Query/Registry RPC method.
type QueryRegistryRequest struct {
	// id is the unique identifier of the registry
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryRegistryRequest) Reset()         { *m = QueryRegistryRequest{} }
func (m *QueryRegistryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRegistryRequest) ProtoMessage()    {}
func (*QueryRegistryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_85f0e510b882f047, []int{6}
}
func (m *QueryRegistryRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRegistryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRegistryRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRegistryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRegistryRequest.Merge(m, src)
}
func (m *QueryRegistryRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRegistryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRegistryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRegistryRequest proto.InternalMessageInfo

func (m *QueryRegistryRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// QueryRegistryResponse is response type for the Query/Registry RPC method.
type QueryRegistryResponse struct {
	// registry is the requested registry
	Registry *Registry `protobuf:"bytes,1,opt,name=registry,proto3" json:"registry,omitempty"`
}

func (m *QueryRegistryResponse) Reset()         { *m = QueryRegistryResponse{} }
func (m *QueryRegistryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRegistryResponse) ProtoMessage()    {}
func (*QueryRegistryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_85f0e510b882f047, []int{7}
}
func (m *QueryRegistryResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRegistryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRegistryResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRegistryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRegistryResponse.Merge(m, src)
}
func (m *QueryRegistryResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRegistryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRegistryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRegistryResponse proto.InternalMessageInfo

func (m *QueryRegistryResponse) GetRegistry() *Registry {
	if m != nil {
		return m.Registry
	}
	return nil
}

// QuerySearchRegistriesByNameRequest is request type for the
// Query/SearchRegistriesByName RPC method.
type QuerySearchRegistriesByNameRequest struct {
	// name is the query string, matched case-insensitively per mode.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// mode selects exact/prefix/suffix/contains matching. Defaults to EXACT.
	Mode RegistryNameMatchMode `protobuf:"varint,2,opt,name=mode,proto3,enum=nvnmchain.anchoring.v1.RegistryNameMatchMode" json:"mode,omitempty"`
	// pagination defines an optional pagination for the request. Only offset
	// and limit are honored; count_total is not supported.
	Pagination *query.PageRequest `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QuerySearchRegistriesByNameRequest) Reset()         { *m = QuerySearchRegistriesByNameRequest{} }
func (m *QuerySearchRegistriesByNameRequest) String() string { return proto.CompactTextString(m) }
func (*QuerySearchRegistriesByNameRequest) ProtoMessage()    {}
func (*QuerySearchRegistriesByNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_85f0e510b882f047, []int{8}
}
func (m *QuerySearchRegistriesByNameRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySearchRegistriesByNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySearchRegistriesByNameRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySearchRegistriesByNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySearchRegistriesByNameRequest.Merge(m, src)
}
func (m *QuerySearchRegistriesByNameRequest) XXX_Size() int {
	return m.Size()
}
func (m *QuerySearchRegistriesByNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySearchRegistriesByNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySearchRegistriesByNameRequest proto.InternalMessageInfo

func (m *QuerySearchRegistriesByNameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *QuerySearchRegistriesByNameRequest) GetMode() RegistryNameMatchMode {
	if m != nil {
		return m.Mode
	}
	return RegistryNameMatchMode_REGISTRY_NAME_MATCH_MODE_UNSPECIFIED
}

func (m *QuerySearchRegistriesByNameRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QuerySearchRegistriesByNameResponse is response type for the
// Query/SearchRegistriesByName RPC method.
type QuerySearchRegistriesByNameResponse struct {
	// registries is a list of registries whose name matched the query.
	Registries []*Registry `protobuf:"bytes,1,rep,name=registries,proto3" json:"registries,omitempty"`
	// pagination defines the pagination in the response.
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QuerySearchRegistriesByNameResponse) Reset()         { *m = QuerySearchRegistriesByNameResponse{} }
func (m *QuerySearchRegistriesByNameResponse) String() string { return proto.CompactTextString(m) }
func (*QuerySearchRegistriesByNameResponse) ProtoMessage()    {}
func (*QuerySearchRegistriesByNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_85f0e510b882f047, []int{9}
}
func (m *QuerySearchRegistriesByNameResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySearchRegistriesByNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySearchRegistriesByNameResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySearchRegistriesByNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySearchRegistriesByNameResponse.Merge(m, src)
}
func (m *QuerySearchRegistriesByNameResponse) XXX_Size() int {
	return m.Size()
}
func (m *QuerySearchRegistriesByNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySearchRegistriesByNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySearchRegistriesByNameResponse proto.InternalMessageInfo

func (m *QuerySearchRegistriesByNameResponse) GetRegistries() []*Registry {
	if m != nil {
		return m.Registries
	}
	return nil
}

func (m *QuerySearchRegistriesByNameResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterEnum("nvnmchain.anchoring.v1.RegistryNameMatchMode", RegistryNameMatchMode_name, RegistryNameMatchMode_value)
	proto.RegisterType((*QueryParamsRequest)(nil), "nvnmchain.anchoring.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "nvnmchain.anchoring.v1.QueryParamsResponse")
	proto.RegisterType((*QueryRecordsRequest)(nil), "nvnmchain.anchoring.v1.QueryRecordsRequest")
	proto.RegisterType((*QueryRecordsResponse)(nil), "nvnmchain.anchoring.v1.QueryRecordsResponse")
	proto.RegisterType((*QueryRegistriesRequest)(nil), "nvnmchain.anchoring.v1.QueryRegistriesRequest")
	proto.RegisterType((*QueryRegistriesResponse)(nil), "nvnmchain.anchoring.v1.QueryRegistriesResponse")
	proto.RegisterType((*QueryRegistryRequest)(nil), "nvnmchain.anchoring.v1.QueryRegistryRequest")
	proto.RegisterType((*QueryRegistryResponse)(nil), "nvnmchain.anchoring.v1.QueryRegistryResponse")
	proto.RegisterType((*QuerySearchRegistriesByNameRequest)(nil), "nvnmchain.anchoring.v1.QuerySearchRegistriesByNameRequest")
	proto.RegisterType((*QuerySearchRegistriesByNameResponse)(nil), "nvnmchain.anchoring.v1.QuerySearchRegistriesByNameResponse")
}

func init() {
	proto.RegisterFile("nvnmchain/anchoring/v1/query.proto", fileDescriptor_85f0e510b882f047)
}

var fileDescriptor_85f0e510b882f047 = []byte{
	// 874 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0xcf, 0x6f, 0xe3, 0x44,
	0x14, 0xce, 0xa4, 0x69, 0xb7, 0x7d, 0x2b, 0xad, 0xca, 0x90, 0x2d, 0x91, 0x41, 0x6e, 0x71, 0xd9,
	0xa5, 0xa4, 0x8d, 0xad, 0x64, 0x01, 0x21, 0xd8, 0x03, 0x69, 0x36, 0x59, 0x22, 0x94, 0x6c, 0x70,
	0x52, 0x54, 0xb8, 0x44, 0x13, 0x7b, 0xe4, 0x58, 0x60, 0x4f, 0xd6, 0x76, 0xa2, 0xcd, 0x11, 0xfe,
	0x02, 0x24, 0x38, 0x80, 0xc4, 0x71, 0x0f, 0x1c, 0xf7, 0x7f, 0xe0, 0xb2, 0x17, 0xc4, 0x22, 0x24,
	0xc4, 0x09, 0xa1, 0x16, 0x89, 0x7f, 0x03, 0x65, 0x3c, 0x76, 0x9b, 0x36, 0x3f, 0xcc, 0xaa, 0x87,
	0xbd, 0x44, 0xe3, 0x99, 0xef, 0x7d, 0xef, 0x7b, 0xdf, 0xb3, 0xdf, 0x04, 0x14, 0x77, 0xe4, 0x3a,
	0x46, 0x9f, 0xd8, 0xae, 0x46, 0x5c, 0xa3, 0xcf, 0x3c, 0xdb, 0xb5, 0xb4, 0x51, 0x51, 0x7b, 0x38,
	0xa4, 0xde, 0x58, 0x1d, 0x78, 0x2c, 0x60, 0x78, 0x2b, 0xc6, 0xa8, 0x31, 0x46, 0x1d, 0x15, 0xa5,
	0x97, 0x88, 0x63, 0xbb, 0x4c, 0xe3, 0xbf, 0x21, 0x54, 0xca, 0x1b, 0xcc, 0x77, 0x98, 0xaf, 0xf5,
	0x88, 0x4f, 0x43, 0x0e, 0x6d, 0x54, 0xec, 0xd1, 0x80, 0x14, 0xb5, 0x01, 0xb1, 0x6c, 0x97, 0x04,
	0x36, 0x73, 0x05, 0x36, 0x6b, 0x31, 0x8b, 0xf1, 0xa5, 0x36, 0x59, 0x89, 0xdd, 0xd7, 0x2c, 0xc6,
	0xac, 0x2f, 0xa9, 0x46, 0x06, 0xb6, 0x46, 0x5c, 0x97, 0x05, 0x3c, 0xc4, 0x17, 0xa7, 0xb7, 0xe6,
	0xc8, 0x35, 0x99, 0x31, 0x74, 0xa8, 0x1b, 0x08, 0xd8, 0xee, 0x1c, 0xd8, 0x80, 0x78, 0xc4, 0x11,
	0x5c, 0x4a, 0x16, 0xf0, 0x27, 0x13, 0x85, 0x2d, 0xbe, 0xa9, 0xd3, 0x87, 0x43, 0xea, 0x07, 0xca,
	0x31, 0xbc, 0x3c, 0xb5, 0xeb, 0x0f, 0x98, 0xeb, 0x53, 0x5c, 0x86, 0xb5, 0x30, 0x38, 0x87, 0x76,
	0xd0, 0xde, 0xf5, 0x92, 0xac, 0xce, 0x36, 0x45, 0x0d, 0xe3, 0x0e, 0x37, 0x9e, 0xfe, 0xb5, 0x9d,
	0xfa, 0xe9, 0xdf, 0x27, 0x79, 0xa4, 0x8b, 0x40, 0xe5, 0x17, 0x24, 0xa8, 0x75, 0x6a, 0x30, 0xcf,
	0x8c, 0x32, 0x62, 0x09, 0xd6, 0x8d, 0x3e, 0x35, 0xbe, 0xf0, 0x87, 0x0e, 0x27, 0xdf, 0xd0, 0xe3,
	0x67, 0xbc, 0x0d, 0xd7, 0x3d, 0x6a, 0xd9, 0x7e, 0xe0, 0x8d, 0xbb, 0xb6, 0x99, 0x4b, 0xef, 0xa0,
	0xbd, 0x8c, 0x0e, 0xd1, 0x56, 0xdd, 0xc4, 0xaf, 0xc2, 0x86, 0xc7, 0xe9, 0x26, 0xc7, 0x2b, 0xfc,
	0x78, 0x3d, 0xdc, 0xa8, 0x9b, 0x38, 0x0b, 0xab, 0xb6, 0x6b, 0xd2, 0x47, 0xb9, 0x0c, 0x3f, 0x08,
	0x1f, 0x70, 0x0d, 0xe0, 0xac, 0x17, 0xb9, 0x55, 0x5e, 0xce, 0x6d, 0x35, 0x6c, 0x9c, 0x3a, 0x69,
	0x9c, 0x1a, 0x36, 0x5f, 0x34, 0x4e, 0x6d, 0x11, 0x8b, 0x0a, 0xad, 0xfa, 0xb9, 0x48, 0xe5, 0x07,
	0x04, 0xd9, 0xe9, 0x7a, 0x84, 0x57, 0xef, 0xc1, 0xb5, 0x50, 0xc2, 0xc4, 0xac, 0x95, 0x45, 0x66,
	0x85, 0x91, 0x7a, 0x04, 0xc7, 0xf7, 0xa7, 0xa4, 0xa5, 0xb9, 0xb4, 0x37, 0x97, 0x4a, 0x0b, 0xd3,
	0x4e, 0x69, 0xfb, 0x0a, 0xc1, 0x96, 0xd0, 0xc6, 0xad, 0xb2, 0x69, 0x6c, 0xf7, 0x05, 0x4b, 0xd1,
	0x25, 0x4b, 0xa7, 0xfd, 0x59, 0x79, 0x6e, 0x7f, 0x1e, 0x23, 0x78, 0xe5, 0x92, 0x06, 0x61, 0xd1,
	0x87, 0x10, 0x65, 0xb4, 0x69, 0xe4, 0xd2, 0xce, 0x7c, 0x97, 0x42, 0x6d, 0xfa, 0xb9, 0x98, 0xab,
	0xb3, 0xea, 0x76, 0xdc, 0x45, 0x91, 0x45, 0xf8, 0x74, 0x03, 0xd2, 0xb1, 0x3d, 0x69, 0xdb, 0x54,
	0x8e, 0xe0, 0xe6, 0x05, 0x9c, 0xa8, 0xe5, 0x2e, 0xac, 0x47, 0xee, 0x89, 0x8f, 0x63, 0x79, 0x25,
	0x71, 0x84, 0xf2, 0x33, 0x02, 0x85, 0xf3, 0xb6, 0x29, 0xf1, 0x8c, 0xfe, 0x99, 0x57, 0x87, 0xe3,
	0x26, 0x71, 0x22, 0x63, 0x31, 0x86, 0x8c, 0x4b, 0x1c, 0x2a, 0x3e, 0x10, 0xbe, 0xc6, 0x65, 0xc8,
	0x38, 0xcc, 0xa4, 0xbc, 0xf8, 0x1b, 0xa5, 0xc2, 0xb2, 0xa4, 0x13, 0xba, 0x06, 0x09, 0x8c, 0x7e,
	0x83, 0x99, 0x54, 0xe7, 0xa1, 0x57, 0xd6, 0xeb, 0x27, 0x08, 0x76, 0x17, 0x56, 0xf1, 0xc2, 0xf5,
	0x3d, 0xff, 0x07, 0x82, 0x9b, 0x33, 0xad, 0xc1, 0x7b, 0xf0, 0x86, 0x5e, 0xbd, 0x5f, 0x6f, 0x77,
	0xf4, 0xcf, 0xba, 0xcd, 0x72, 0xa3, 0xda, 0x6d, 0x94, 0x3b, 0x95, 0x8f, 0xba, 0x8d, 0x07, 0xf7,
	0xaa, 0xdd, 0xa3, 0x66, 0xbb, 0x55, 0xad, 0xd4, 0x6b, 0xf5, 0xea, 0xbd, 0xcd, 0x14, 0x56, 0x40,
	0x9e, 0x8b, 0xac, 0x1e, 0x97, 0x2b, 0x9d, 0x4d, 0x84, 0x77, 0x61, 0x7b, 0x2e, 0xa6, 0xa5, 0x57,
	0x6b, 0xf5, 0xe3, 0xcd, 0xf4, 0x42, 0x50, 0xfb, 0xa8, 0x36, 0x01, 0xad, 0xe0, 0x5b, 0xf0, 0xfa,
	0x5c, 0x50, 0xe5, 0x41, 0xb3, 0x53, 0xae, 0x37, 0xdb, 0x9b, 0x99, 0xd2, 0x6f, 0x6b, 0xb0, 0xca,
	0x7b, 0x81, 0xbf, 0x43, 0xb0, 0x16, 0xce, 0x63, 0x9c, 0x9f, 0x67, 0xf2, 0xe5, 0x2b, 0x40, 0xda,
	0x4f, 0x84, 0x0d, 0x2d, 0x55, 0x8a, 0x5f, 0xff, 0xfe, 0xcf, 0xb7, 0xe9, 0x7d, 0xfc, 0x96, 0xd6,
	0xfc, 0xb4, 0xd9, 0x28, 0x54, 0xf8, 0xa5, 0xb3, 0xf0, 0xfa, 0xc1, 0xdf, 0x23, 0xb8, 0x26, 0x66,
	0x26, 0x5e, 0x9c, 0x6b, 0xfa, 0xa6, 0x90, 0x0e, 0x92, 0x81, 0x85, 0xb2, 0x12, 0x57, 0x76, 0x80,
	0xf3, 0x09, 0x94, 0x45, 0x03, 0xf8, 0x31, 0x02, 0x38, 0x7b, 0x79, 0xb1, 0xba, 0x24, 0xe1, 0x85,
	0xd9, 0x2a, 0x69, 0x89, 0xf1, 0x42, 0xe3, 0x3b, 0x5c, 0xa3, 0x86, 0x0b, 0x89, 0x34, 0xc6, 0xba,
	0x7e, 0x44, 0xb0, 0x1e, 0xbd, 0xbb, 0xf8, 0x20, 0x49, 0xd2, 0x68, 0xac, 0x49, 0x85, 0x84, 0x68,
	0x21, 0xf0, 0x0e, 0x17, 0x58, 0xc0, 0xfb, 0xc9, 0x05, 0x8e, 0xf1, 0xaf, 0x08, 0xb6, 0x66, 0x0f,
	0x02, 0xfc, 0xfe, 0xc2, 0xf4, 0x0b, 0x67, 0xa0, 0xf4, 0xc1, 0x73, 0xc5, 0x8a, 0x42, 0xee, 0xf2,
	0x42, 0xde, 0xc5, 0x6f, 0xff, 0x2f, 0xa7, 0x35, 0x9f, 0xb3, 0x1e, 0x7e, 0xfc, 0xf4, 0x44, 0x46,
	0xcf, 0x4e, 0x64, 0xf4, 0xf7, 0x89, 0x8c, 0xbe, 0x39, 0x95, 0x53, 0xcf, 0x4e, 0xe5, 0xd4, 0x9f,
	0xa7, 0x72, 0xea, 0xf3, 0xa2, 0x65, 0x07, 0xfd, 0x61, 0x4f, 0x35, 0x98, 0x33, 0x9b, 0xf9, 0xd1,
	0x39, 0xee, 0x60, 0x3c, 0xa0, 0x7e, 0x6f, 0x8d, 0xff, 0xff, 0xba, 0xf3, 0x5f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xf1, 0x12, 0xee, 0x05, 0x7c, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Records queries documents based on filters
	Records(ctx context.Context, in *QueryRecordsRequest, opts ...grpc.CallOption) (*QueryRecordsResponse, error)
	// Registries queries all registries with pagination
	Registries(ctx context.Context, in *QueryRegistriesRequest, opts ...grpc.CallOption) (*QueryRegistriesResponse, error)
	// Registry queries a specific registry by id
	Registry(ctx context.Context, in *QueryRegistryRequest, opts ...grpc.CallOption) (*QueryRegistryResponse, error)
	// SearchRegistriesByName looks up registries by name using an opt-in local
	// name index. It returns codes.FailedPrecondition on
	// nodes that do not have the name index enabled (see app.toml
	// [anchoring-name-index]); it is not part of the deterministic state
	// machine and results may differ across nodes depending on whether/when
	// each node enabled and backfilled its index.
	SearchRegistriesByName(ctx context.Context, in *QuerySearchRegistriesByNameRequest, opts ...grpc.CallOption) (*QuerySearchRegistriesByNameResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/nvnmchain.anchoring.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Records(ctx context.Context, in *QueryRecordsRequest, opts ...grpc.CallOption) (*QueryRecordsResponse, error) {
	out := new(QueryRecordsResponse)
	err := c.cc.Invoke(ctx, "/nvnmchain.anchoring.v1.Query/Records", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Registries(ctx context.Context, in *QueryRegistriesRequest, opts ...grpc.CallOption) (*QueryRegistriesResponse, error) {
	out := new(QueryRegistriesResponse)
	err := c.cc.Invoke(ctx, "/nvnmchain.anchoring.v1.Query/Registries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Registry(ctx context.Context, in *QueryRegistryRequest, opts ...grpc.CallOption) (*QueryRegistryResponse, error) {
	out := new(QueryRegistryResponse)
	err := c.cc.Invoke(ctx, "/nvnmchain.anchoring.v1.Query/Registry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SearchRegistriesByName(ctx context.Context, in *QuerySearchRegistriesByNameRequest, opts ...grpc.CallOption) (*QuerySearchRegistriesByNameResponse, error) {
	out := new(QuerySearchRegistriesByNameResponse)
	err := c.cc.Invoke(ctx, "/nvnmchain.anchoring.v1.Query/SearchRegistriesByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Records queries documents based on filters
	Records(context.Context, *QueryRecordsRequest) (*QueryRecordsResponse, error)
	// Registries queries all registries with pagination
	Registries(context.Context, *QueryRegistriesRequest) (*QueryRegistriesResponse, error)
	// Registry queries a specific registry by id
	Registry(context.Context, *QueryRegistryRequest) (*QueryRegistryResponse, error)
	// SearchRegistriesByName looks up registries by name using an opt-in local
	// name index. It returns codes.FailedPrecondition on
	// nodes that do not have the name index enabled (see app.toml
	// [anchoring-name-index]); it is not part of the deterministic state
	// machine and results may differ across nodes depending on whether/when
	// each node enabled and backfilled its index.
	SearchRegistriesByName(context.Context, *QuerySearchRegistriesByNameRequest) (*QuerySearchRegistriesByNameResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) Records(ctx context.Context, req *QueryRecordsRequest) (*QueryRecordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Records not implemented")
}
func (*UnimplementedQueryServer) Registries(ctx context.Context, req *QueryRegistriesRequest) (*QueryRegistriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Registries not implemented")
}
func (*UnimplementedQueryServer) Registry(ctx context.Context, req *QueryRegistryRequest) (*QueryRegistryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Registry not implemented")
}
func (*UnimplementedQueryServer) SearchRegistriesByName(ctx context.Context, req *QuerySearchRegistriesByNameRequest) (*QuerySearchRegistriesByNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchRegistriesByName not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nvnmchain.anchoring.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Records_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Records(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nvnmchain.anchoring.v1.Query/Records",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Records(ctx, req.(*QueryRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Registries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRegistriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Registries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nvnmchain.anchoring.v1.Query/Registries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Registries(ctx, req.(*QueryRegistriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Registry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRegistryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Registry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nvnmchain.anchoring.v1.Query/Registry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Registry(ctx, req.(*QueryRegistryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SearchRegistriesByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySearchRegistriesByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SearchRegistriesByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nvnmchain.anchoring.v1.Query/SearchRegistriesByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SearchRegistriesByName(ctx, req.(*QuerySearchRegistriesByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nvnmchain.anchoring.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Records",
			Handler:    _Query_Records_Handler,
		},
		{
			MethodName: "Registries",
			Handler:    _Query_Registries_Handler,
		},
		{
			MethodName: "Registry",
			Handler:    _Query_Registry_Handler,
		},
		{
			MethodName: "SearchRegistriesByName",
			Handler:    _Query_SearchRegistriesByName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nvnmchain/anchoring/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryRecordsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRecordsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRecordsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.Index != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x20
	}
	if m.RecordId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.RecordId))
		i--
		dAtA[i] = 0x18
	}
	if m.RegistryId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.RegistryId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Checksum) > 0 {
		i -= len(m.Checksum)
		copy(dAtA[i:], m.Checksum)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Checksum)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryRecordsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRecordsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRecordsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Records) > 0 {
		for iNdEx := len(m.Records) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Records[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryRegistriesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRegistriesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRegistriesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.RegistryId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.RegistryId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryRegistriesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRegistriesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRegistriesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Registries) > 0 {
		for iNdEx := len(m.Registries) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Registries[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryRegistryRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRegistryRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRegistryRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryRegistryResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRegistryResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRegistryResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Registry != nil {
		{
			size, err := m.Registry.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QuerySearchRegistriesByNameRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySearchRegistriesByNameRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySearchRegistriesByNameRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.Mode != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Mode))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QuerySearchRegistriesByNameResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySearchRegistriesByNameResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySearchRegistriesByNameResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Registries) > 0 {
		for iNdEx := len(m.Registries) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Registries[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryRecordsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Checksum)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.RegistryId != 0 {
		n += 1 + sovQuery(uint64(m.RegistryId))
	}
	if m.RecordId != 0 {
		n += 1 + sovQuery(uint64(m.RecordId))
	}
	if m.Index != 0 {
		n += 1 + sovQuery(uint64(m.Index))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryRecordsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Records) > 0 {
		for _, e := range m.Records {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryRegistriesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RegistryId != 0 {
		n += 1 + sovQuery(uint64(m.RegistryId))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryRegistriesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Registries) > 0 {
		for _, e := range m.Registries {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryRegistryRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryRegistryResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Registry != nil {
		l = m.Registry.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QuerySearchRegistriesByNameRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Mode != 0 {
		n += 1 + sovQuery(uint64(m.Mode))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QuerySearchRegistriesByNameResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Registries) > 0 {
		for _, e := range m.Registries {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRecordsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRecordsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRecordsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Checksum", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Checksum = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegistryId", wireType)
			}
			m.RegistryId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RegistryId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecordId", wireType)
			}
			m.RecordId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RecordId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRecordsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRecordsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRecordsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Records", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Records = append(m.Records, &Record{})
			if err := m.Records[len(m.Records)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRegistriesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRegistriesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRegistriesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegistryId", wireType)
			}
			m.RegistryId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RegistryId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRegistriesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRegistriesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRegistriesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Registries", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Registries = append(m.Registries, &Registry{})
			if err := m.Registries[len(m.Registries)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRegistryRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRegistryRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRegistryRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRegistryResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRegistryResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRegistryResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Registry", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Registry == nil {
				m.Registry = &Registry{}
			}
			if err := m.Registry.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QuerySearchRegistriesByNameRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySearchRegistriesByNameRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySearchRegistriesByNameRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mode", wireType)
			}
			m.Mode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Mode |= RegistryNameMatchMode(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QuerySearchRegistriesByNameResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySearchRegistriesByNameResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySearchRegistriesByNameResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Registries", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Registries = append(m.Registries, &Registry{})
			if err := m.Registries[len(m.Registries)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
