syntax = "proto3";
package mantrachain.tax.v1;

import "amino/amino.proto";
import "cosmos_proto/cosmos.proto";
import "gogoproto/gogo.proto";

option go_package = "github.com/MANTRA-Chain/nvnmchain/x/tax/types";

// Params defines the parameters for the module.
message Params {
  option (amino.name) = "nvnmchain/x/tax/Params";
  option (gogoproto.equal) = true;

  string tax = 1 [
    (gogoproto.customtype) = "cosmossdk.io/math.LegacyDec",
    (amino.dont_omitempty) = true,
    (gogoproto.nullable) = false
  ];

  string tax_address = 2 [
    (cosmos_proto.scalar) = "cosmos.AddressString",
    (amino.dont_omitempty) = true
  ];

}
