defaults:
  actions:
    backport:
      assignees:
        - "{{ author }}"

queue_rules:
  - name: default
    queue_conditions:
      - "#approved-reviews-by>=2"
      - base=main
      - label=A:automerge
    merge_conditions:
      - "#approved-reviews-by>=1"
    commit_message_template: |
      {{ title }} (#{{ number }})
      {{ body }}
    merge_method: squash

pull_request_rules:
  - name: backport patches to release/v1.0.0-rcx branch
    conditions:
      - base=main
      - label=A:backport/v1.0.0-rcx
    actions:
      backport:
        branches:
          - release/v1.0.0-rcx
  - name: backport patches to sovereign branch
    conditions:
      - base=main
      - label=A:backport/sovereign
    actions:
      backport:
        branches:
          - sovereign
