---
version: 2
project_name: nvnmchaind

env:
  - GO111MODULE=on
  - CGO_ENABLED=1

builds:
  - id: nvnmchaind-darwin-amd64
    main: ./cmd/nvnmchaind/main.go
    binary: nvnmchaind
    env:
      - CC=o64-clang
      - CGO_LDFLAGS=-L/lib
    goos:
      - darwin
    goarch:
      - amd64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X github.com/cosmos/cosmos-sdk/version.Name=nvnmchain
      - -X github.com/cosmos/cosmos-sdk/version.AppName=nvnmchaind
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .ShortCommit }}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger
      - -X github.com/cometbft/cometbft/version.TMCoreSemVer={{ .Env.CMT_VERSION }}
      - -w -s
      - -linkmode=external
    tags:
      - netgo
      - ledger
      - pebbledb
      - uint256

  - id: nvnmchaind-darwin-arm64
    main: ./cmd/nvnmchaind/main.go
    binary: nvnmchaind
    env:
      - CC=oa64-clang
      - CGO_LDFLAGS=-L/lib
    goos:
      - darwin
    goarch:
      - arm64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X github.com/cosmos/cosmos-sdk/version.Name=nvnmchain
      - -X github.com/cosmos/cosmos-sdk/version.AppName=nvnmchaind
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .ShortCommit }}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger
      - -X github.com/cometbft/cometbft/version.TMCoreSemVer={{ .Env.CMT_VERSION }}
      - -w -s
      - -linkmode=external
    tags:
      - netgo
      - ledger
      - pebbledb
      - uint256

  - id: nvnmchaind-linux-amd64
    main: ./cmd/nvnmchaind
    binary: nvnmchaind
    hooks:
      pre:
        - apk add --update linux-headers
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X github.com/cosmos/cosmos-sdk/version.Name=nvnmchain
      - -X github.com/cosmos/cosmos-sdk/version.AppName=nvnmchaind
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .ShortCommit }}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger,muslc,osusergo
      - -X github.com/cometbft/cometbft/version.TMCoreSemVer={{ .Env.CMT_VERSION }}
      - -w -s
      - -linkmode=external
      - -extldflags '-Wl,-z,muldefs -static -lm'
    tags:
      - netgo
      - ledger
      - muslc
      - osusergo
      - pebbledb
      - uint256

  - id: nvnmchaind-linux-arm64
    main: ./cmd/nvnmchaind
    binary: nvnmchaind
    hooks:
      pre:
        - apk add --update linux-headers
    goos:
      - linux
    goarch:
      - arm64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X github.com/cosmos/cosmos-sdk/version.Name=nvnmchain
      - -X github.com/cosmos/cosmos-sdk/version.AppName=nvnmchaind
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .ShortCommit }}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger,muslc,osusergo
      - -X github.com/cometbft/cometbft/version.TMCoreSemVer={{ .Env.CMT_VERSION }}
      - -w -s
      - -linkmode=external
      - -extldflags '-Wl,-z,muldefs -static -lm'
    tags:
      - netgo
      - ledger
      - muslc
      - osusergo
      - pebbledb
      - uint256

archives:
  - id: zipped
    builds:
      - nvnmchaind-linux-amd64
      - nvnmchaind-linux-arm64
      - nvnmchaind-darwin-amd64
      - nvnmchaind-darwin-arm64
    name_template: "{{.ProjectName}}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format: tar.gz
    files:
      - none*
  - id: binaries
    builds:
      - nvnmchaind-linux-amd64
      - nvnmchaind-linux-arm64
      - nvnmchaind-darwin-amd64
      - nvnmchaind-darwin-arm64
    name_template: "{{.ProjectName}}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format: binary
    files:
      - none*

checksum:
  name_template: "sha256sum.txt"
  algorithm: sha256

# Docs: https://goreleaser.com/customization/changelog/
changelog:
  disable: true

# Docs: https://goreleaser.com/customization/release/
release:
  github:
    owner: "{{ .Env.REPO_OWNER }}"
    name: "{{ .Env.REPO_NAME }}"
  replace_existing_draft: true
  header: |
    < DESCRIPTION OF RELEASE >

    ## Changelog

    See the full changelog [here](https://github.com/{{ .Env.REPO_OWNER }}/{{ .Env.REPO_NAME }}/blob/v{{ .Version }}/CHANGELOG.md)

    #### 🔨 Build from source

    If you prefer to build from source, you can use the following commands:

    ````bash
    git clone https://github.com/{{ .Env.REPO_OWNER }}/{{ .Env.REPO_NAME }}
    cd nvnmchain && git checkout v{{ .Version }}
    make install
    ````

  name_template: "Nvnmchain v{{.Version}}"
  mode: replace
  draft: true

# Docs: https://goreleaser.com/customization/announce/
# We could automatically announce the release in
# - discord
# - slack
# - twitter
# - webhooks
# - telegram
# - reddit
#
# announce:
# discord:
#   enabled: true
#   message_template: 'New {{.Tag}} is out!'
