syntax = "proto3";
package mantrachain.document.v1;

import "amino/amino.proto";
import "gogoproto/gogo.proto";
import "mantrachain/document/v1/params.proto";

option go_package = "github.com/MANTRA-Chain/inveniam/x/document/types";

message Document {
    option (gogoproto.equal) = true;
    // The name or identifier of the document.
    string document = 1;

    // The token denomination associated with the document.
    string denom = 2;

    // A link to where the document is stored (e.g., IPFS).
    string uri = 3;

    // A hash of the document to verify its integrity.
    string checksum = 4;

    // The algorithm used to generate the checksum (e.g., SHA-256).
    string checksum_algo = 5;

    // The timestamp when the document was created or registered.
    string timestamp = 6;

    // The Financial Instrument Global Identifier.
    string figi = 7;

    // An identifier for an individual.
    string individual_id = 8;
}