syntax = "proto3";
package nvnmchain.anchoring.v1;

import "amino/amino.proto";
import "gogoproto/gogo.proto";
import "nvnmchain/anchoring/v1/params.proto";

option go_package = "github.com/NVNM-Chain/nvnmchain/x/anchoring/types";

message Registry {
  // Unique ID (auto-incrementing uint64 is standard for Cosmos collections)
  uint64 id = 1;

  // Name of the registry. Not guaranteed unique — multiple registries may share
  // the same name.
  string name = 2;

  // Description of what this registry verifies
  string description = 3;

  // The global creator. Usually has immutable admin rights.
  string creator = 4;

  // Timestamp of creation
  string created_at = 5;

  // Additional metadata associated with the registry in stringified JSON format.
  string metadata = 6;
}

message Record {
  option (gogoproto.equal) = true;
  reserved 1;
  reserved "registry";

  // A link to where the document is stored (e.g., IPFS).
  string uri = 2;

  // A hash of the document to verify its integrity.
  string checksum = 3;

  // The algorithm used to generate the checksum (e.g., SHA-256).
  string checksum_algo = 4;

  // Additional metadata associated with the document in stringified JSON format.
  string metadata = 5;

  // The timestamp when the document was created or registered.
  string timestamp = 6;

  // The current status of the document (e.g., active, redacted).
  string status = 7;

  // The unique identifier for the record within the registry.
  uint64 record_id = 8;

  // A index counter for the record.
  uint64 index = 9;

  // Indicates if this is the latest version of the record.
  bool is_latest = 10;

  // The id of the registry this record belongs to.
  uint64 registry_id = 11;
}