//go:build uint256

// Code generated by go-abi. DO NOT EDIT.

package precompile

import (
	"encoding/binary"
	"io"

	cmn "github.com/NVNM-Chain/nvnmchain/precompiles"
	"github.com/ethereum/go-ethereum/common"
	"github.com/yihuang/go-abi"
)

// Function selectors
var (
	// addRecord((string,string,string,string,string,string,uint64,uint64,bool,uint64))
	AddRecordSelector = [4]byte{0x64, 0xd2, 0x52, 0x95}
	// addRegistry(string,string,string)
	AddRegistrySelector = [4]byte{0x31, 0x8b, 0x38, 0xb1}
	// grantRole(uint64,string,address,string)
	GrantRoleSelector = [4]byte{0xb8, 0xfd, 0xd1, 0xa7}
	// records(uint64,string,uint64,uint64,(bytes,uint64,uint64,bool,bool))
	RecordsSelector = [4]byte{0xc7, 0xbe, 0x5e, 0x37}
	// registries(uint64,(bytes,uint64,uint64,bool,bool))
	RegistriesSelector = [4]byte{0x17, 0xbd, 0x3e, 0x65}
	// revokeRole(uint64,string,address,string)
	RevokeRoleSelector = [4]byte{0xac, 0xd5, 0x8b, 0xc7}
	// updateRecordStatus(uint64,uint64,uint64,string)
	UpdateRecordStatusSelector = [4]byte{0x97, 0xb4, 0x0c, 0x25}
)

// Big endian integer versions of function selectors
const (
	AddRecordID          = 1691505301
	AddRegistryID        = 831207601
	GrantRoleID          = 3103642023
	RecordsID            = 3351141943
	RegistriesID         = 398278245
	RevokeRoleID         = 2899676103
	UpdateRecordStatusID = 2545159205
)

const RecordStaticSize = 320

var _ abi.Tuple = (*Record)(nil)

// Record represents an ABI tuple
type Record struct {
	Uri          string
	Checksum     string
	ChecksumAlgo string
	Metadata     string
	Timestamp    string
	Status       string
	RecordId     uint64
	Index        uint64
	IsLatest     bool
	RegistryId   uint64
}

// EncodedSize returns the total encoded size of Record
func (t Record) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += abi.SizeString(t.Uri)
	dynamicSize += abi.SizeString(t.Checksum)
	dynamicSize += abi.SizeString(t.ChecksumAlgo)
	dynamicSize += abi.SizeString(t.Metadata)
	dynamicSize += abi.SizeString(t.Timestamp)
	dynamicSize += abi.SizeString(t.Status)

	return RecordStaticSize + dynamicSize
}

// EncodeTo encodes Record to ABI bytes in the provided buffer
func (value Record) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := RecordStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field Uri: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Uri, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field Checksum: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Checksum, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field ChecksumAlgo: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[64+24:64+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.ChecksumAlgo, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field Metadata: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[96+24:96+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Metadata, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field Timestamp: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[128+24:128+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Timestamp, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field Status: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[160+24:160+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Status, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field RecordId: uint64
	if _, err := abi.EncodeUint64(value.RecordId, buf[192:]); err != nil {
		return 0, err
	}

	// Field Index: uint64
	if _, err := abi.EncodeUint64(value.Index, buf[224:]); err != nil {
		return 0, err
	}

	// Field IsLatest: bool
	if _, err := abi.EncodeBool(value.IsLatest, buf[256:]); err != nil {
		return 0, err
	}

	// Field RegistryId: uint64
	if _, err := abi.EncodeUint64(value.RegistryId, buf[288:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes Record to ABI bytes
func (value Record) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes Record from ABI bytes in the provided buffer
func (t *Record) Decode(data []byte) (int, error) {
	if len(data) < 320 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err    error
		n      int
		offset int
	)
	dynamicOffset := 320
	// Decode dynamic field Uri
	{
		offset, err = abi.DecodeSize(data[0:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.Uri, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode dynamic field Checksum
	{
		offset, err = abi.DecodeSize(data[32:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.Checksum, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode dynamic field ChecksumAlgo
	{
		offset, err = abi.DecodeSize(data[64:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.ChecksumAlgo, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode dynamic field Metadata
	{
		offset, err = abi.DecodeSize(data[96:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.Metadata, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode dynamic field Timestamp
	{
		offset, err = abi.DecodeSize(data[128:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.Timestamp, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode dynamic field Status
	{
		offset, err = abi.DecodeSize(data[160:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.Status, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode static field RecordId: uint64
	t.RecordId, _, err = abi.DecodeUint64(data[192:])
	if err != nil {
		return 0, err
	}
	// Decode static field Index: uint64
	t.Index, _, err = abi.DecodeUint64(data[224:])
	if err != nil {
		return 0, err
	}
	// Decode static field IsLatest: bool
	t.IsLatest, _, err = abi.DecodeBool(data[256:])
	if err != nil {
		return 0, err
	}
	// Decode static field RegistryId: uint64
	t.RegistryId, _, err = abi.DecodeUint64(data[288:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

const RegistryStaticSize = 192

var _ abi.Tuple = (*Registry)(nil)

// Registry represents an ABI tuple
type Registry struct {
	Id          uint64
	Name        string
	Description string
	Creator     string
	CreatedAt   string
	Metadata    string
}

// EncodedSize returns the total encoded size of Registry
func (t Registry) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += abi.SizeString(t.Name)
	dynamicSize += abi.SizeString(t.Description)
	dynamicSize += abi.SizeString(t.Creator)
	dynamicSize += abi.SizeString(t.CreatedAt)
	dynamicSize += abi.SizeString(t.Metadata)

	return RegistryStaticSize + dynamicSize
}

// EncodeTo encodes Registry to ABI bytes in the provided buffer
func (value Registry) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := RegistryStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field Id: uint64
	if _, err := abi.EncodeUint64(value.Id, buf[0:]); err != nil {
		return 0, err
	}

	// Field Name: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Name, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field Description: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[64+24:64+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Description, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field Creator: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[96+24:96+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Creator, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field CreatedAt: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[128+24:128+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.CreatedAt, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field Metadata: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[160+24:160+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Metadata, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	return dynamicOffset, nil
}

// Encode encodes Registry to ABI bytes
func (value Registry) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes Registry from ABI bytes in the provided buffer
func (t *Registry) Decode(data []byte) (int, error) {
	if len(data) < 192 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err    error
		n      int
		offset int
	)
	dynamicOffset := 192
	// Decode static field Id: uint64
	t.Id, _, err = abi.DecodeUint64(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode dynamic field Name
	{
		offset, err = abi.DecodeSize(data[32:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.Name, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode dynamic field Description
	{
		offset, err = abi.DecodeSize(data[64:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.Description, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode dynamic field Creator
	{
		offset, err = abi.DecodeSize(data[96:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.Creator, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode dynamic field CreatedAt
	{
		offset, err = abi.DecodeSize(data[128:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.CreatedAt, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode dynamic field Metadata
	{
		offset, err = abi.DecodeSize(data[160:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.Metadata, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	return dynamicOffset, nil
}

// EncodeRecordSlice encodes (string,string,string,string,string,string,uint64,uint64,bool,uint64)[] to ABI bytes
func EncodeRecordSlice(value []Record, buf []byte) (int, error) {
	// Encode length
	binary.BigEndian.PutUint64(buf[24:32], uint64(len(value)))
	buf = buf[32:]

	// Encode elements with dynamic types
	var offset int
	dynamicOffset := len(value) * 32
	for _, elem := range value {
		// Write offset for element
		offset += 32
		binary.BigEndian.PutUint64(buf[offset-8:offset], uint64(dynamicOffset))

		// Write element at dynamic region
		n, err := elem.EncodeTo(buf[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}

	return dynamicOffset + 32, nil
}

// EncodeRegistrySlice encodes (uint64,string,string,string,string,string)[] to ABI bytes
func EncodeRegistrySlice(value []Registry, buf []byte) (int, error) {
	// Encode length
	binary.BigEndian.PutUint64(buf[24:32], uint64(len(value)))
	buf = buf[32:]

	// Encode elements with dynamic types
	var offset int
	dynamicOffset := len(value) * 32
	for _, elem := range value {
		// Write offset for element
		offset += 32
		binary.BigEndian.PutUint64(buf[offset-8:offset], uint64(dynamicOffset))

		// Write element at dynamic region
		n, err := elem.EncodeTo(buf[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}

	return dynamicOffset + 32, nil
}

// SizeRecordSlice returns the encoded size of (string,string,string,string,string,string,uint64,uint64,bool,uint64)[]
func SizeRecordSlice(value []Record) int {
	size := 32 + 32*len(value) // length + offset pointers for dynamic elements
	for _, elem := range value {
		size += elem.EncodedSize()
	}
	return size
}

// SizeRegistrySlice returns the encoded size of (uint64,string,string,string,string,string)[]
func SizeRegistrySlice(value []Registry) int {
	size := 32 + 32*len(value) // length + offset pointers for dynamic elements
	for _, elem := range value {
		size += elem.EncodedSize()
	}
	return size
}

// DecodeRecordSlice decodes (string,string,string,string,string,string,uint64,uint64,bool,uint64)[] from ABI bytes
func DecodeRecordSlice(data []byte) ([]Record, int, error) {
	// Decode length
	if len(data) < 32 {
		return nil, 0, io.ErrUnexpectedEOF
	}
	length, err := abi.DecodeSize(data)
	if err != nil {
		return nil, 0, err
	}
	data = data[32:]
	if length > len(data) || length*32 > len(data) {
		return nil, 0, io.ErrUnexpectedEOF
	}
	var (
		n      int
		offset int
	)
	// Decode elements with dynamic types
	result := make([]Record, length)
	dynamicOffset := length * 32
	for i := 0; i < length; i++ {
		tmp, err := abi.DecodeSize(data[offset:])
		if err != nil {
			return nil, 0, err
		}
		offset += 32

		if dynamicOffset != tmp {
			return nil, 0, abi.ErrInvalidOffsetForSliceElement
		}
		n, err = result[i].Decode(data[dynamicOffset:])
		if err != nil {
			return nil, 0, err
		}
		dynamicOffset += n
	}
	return result, dynamicOffset + 32, nil
}

// DecodeRegistrySlice decodes (uint64,string,string,string,string,string)[] from ABI bytes
func DecodeRegistrySlice(data []byte) ([]Registry, int, error) {
	// Decode length
	if len(data) < 32 {
		return nil, 0, io.ErrUnexpectedEOF
	}
	length, err := abi.DecodeSize(data)
	if err != nil {
		return nil, 0, err
	}
	data = data[32:]
	if length > len(data) || length*32 > len(data) {
		return nil, 0, io.ErrUnexpectedEOF
	}
	var (
		n      int
		offset int
	)
	// Decode elements with dynamic types
	result := make([]Registry, length)
	dynamicOffset := length * 32
	for i := 0; i < length; i++ {
		tmp, err := abi.DecodeSize(data[offset:])
		if err != nil {
			return nil, 0, err
		}
		offset += 32

		if dynamicOffset != tmp {
			return nil, 0, abi.ErrInvalidOffsetForSliceElement
		}
		n, err = result[i].Decode(data[dynamicOffset:])
		if err != nil {
			return nil, 0, err
		}
		dynamicOffset += n
	}
	return result, dynamicOffset + 32, nil
}

var _ abi.Method = (*AddRecordCall)(nil)

const AddRecordCallStaticSize = 32

var _ abi.Tuple = (*AddRecordCall)(nil)

// AddRecordCall represents an ABI tuple
type AddRecordCall struct {
	Record Record
}

// EncodedSize returns the total encoded size of AddRecordCall
func (t AddRecordCall) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += t.Record.EncodedSize()

	return AddRecordCallStaticSize + dynamicSize
}

// EncodeTo encodes AddRecordCall to ABI bytes in the provided buffer
func (value AddRecordCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := AddRecordCallStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field Record: (string,string,string,string,string,string,uint64,uint64,bool,uint64)
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = value.Record.EncodeTo(buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	return dynamicOffset, nil
}

// Encode encodes AddRecordCall to ABI bytes
func (value AddRecordCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes AddRecordCall from ABI bytes in the provided buffer
func (t *AddRecordCall) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err    error
		n      int
		offset int
	)
	dynamicOffset := 32
	// Decode dynamic field Record
	{
		offset, err = abi.DecodeSize(data[0:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		n, err = t.Record.Decode(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	return dynamicOffset, nil
}

// GetMethodName returns the function name
func (t AddRecordCall) GetMethodName() string {
	return "addRecord"
}

// GetMethodID returns the function id
func (t AddRecordCall) GetMethodID() uint32 {
	return AddRecordID
}

// GetMethodSelector returns the function selector
func (t AddRecordCall) GetMethodSelector() [4]byte {
	return AddRecordSelector
}

// EncodeWithSelector encodes addRecord arguments to ABI bytes including function selector
func (t AddRecordCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], AddRecordSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewAddRecordCall constructs a new AddRecordCall
func NewAddRecordCall(
	record Record,
) *AddRecordCall {
	return &AddRecordCall{
		Record: record,
	}
}

const AddRecordReturnStaticSize = 32

var _ abi.Tuple = (*AddRecordReturn)(nil)
var _ abi.PackedTuple = (*AddRecordReturn)(nil)

// AddRecordReturn represents an ABI tuple
type AddRecordReturn struct {
	RecordId uint64
}

// EncodedSize returns the total encoded size of AddRecordReturn
func (t AddRecordReturn) EncodedSize() int {
	dynamicSize := 0

	return AddRecordReturnStaticSize + dynamicSize
}

// EncodeTo encodes AddRecordReturn to ABI bytes in the provided buffer
func (value AddRecordReturn) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := AddRecordReturnStaticSize // Start dynamic data after static section
	// Field RecordId: uint64
	if _, err := abi.EncodeUint64(value.RecordId, buf[0:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes AddRecordReturn to ABI bytes
func (value AddRecordReturn) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes AddRecordReturn from ABI bytes in the provided buffer
func (t *AddRecordReturn) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 32
	// Decode static field RecordId: uint64
	t.RecordId, _, err = abi.DecodeUint64(data[0:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

// PackedEncodedSize returns the packed encoded size of AddRecordReturn
func (t AddRecordReturn) PackedEncodedSize() int {
	return 8
}

// PackedEncodeTo encodes AddRecordReturn to packed ABI bytes in the provided buffer
func (value AddRecordReturn) PackedEncodeTo(buf []byte) (int, error) {
	// Encode tuple fields sequentially (packed, no dynamic section)
	var (
		offset int
		n      int
		err    error
	)
	// Field RecordId: uint64
	n, err = abi.PackedEncodeUint64(value.RecordId, buf[offset:])
	if err != nil {
		return 0, err
	}
	offset += n

	return offset, nil
}

// PackedEncode encodes AddRecordReturn to packed ABI bytes
func (value AddRecordReturn) PackedEncode() ([]byte, error) {
	buf := make([]byte, value.PackedEncodedSize())
	if _, err := value.PackedEncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// PackedDecode decodes AddRecordReturn from packed ABI bytes
func (t *AddRecordReturn) PackedDecode(data []byte) (int, error) {
	if len(data) < 8 {
		return 0, io.ErrUnexpectedEOF
	}
	var err error
	// Decode field RecordId: uint64
	t.RecordId, _, err = abi.PackedDecodeUint64(data[0:])
	if err != nil {
		return 0, err
	}
	return 8, nil
}

var _ abi.Method = (*AddRegistryCall)(nil)

const AddRegistryCallStaticSize = 96

var _ abi.Tuple = (*AddRegistryCall)(nil)

// AddRegistryCall represents an ABI tuple
type AddRegistryCall struct {
	Name        string
	Description string
	Metadata    string
}

// EncodedSize returns the total encoded size of AddRegistryCall
func (t AddRegistryCall) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += abi.SizeString(t.Name)
	dynamicSize += abi.SizeString(t.Description)
	dynamicSize += abi.SizeString(t.Metadata)

	return AddRegistryCallStaticSize + dynamicSize
}

// EncodeTo encodes AddRegistryCall to ABI bytes in the provided buffer
func (value AddRegistryCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := AddRegistryCallStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field Name: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Name, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field Description: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Description, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field Metadata: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[64+24:64+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Metadata, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	return dynamicOffset, nil
}

// Encode encodes AddRegistryCall to ABI bytes
func (value AddRegistryCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes AddRegistryCall from ABI bytes in the provided buffer
func (t *AddRegistryCall) Decode(data []byte) (int, error) {
	if len(data) < 96 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err    error
		n      int
		offset int
	)
	dynamicOffset := 96
	// Decode dynamic field Name
	{
		offset, err = abi.DecodeSize(data[0:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.Name, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode dynamic field Description
	{
		offset, err = abi.DecodeSize(data[32:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.Description, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode dynamic field Metadata
	{
		offset, err = abi.DecodeSize(data[64:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.Metadata, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	return dynamicOffset, nil
}

// GetMethodName returns the function name
func (t AddRegistryCall) GetMethodName() string {
	return "addRegistry"
}

// GetMethodID returns the function id
func (t AddRegistryCall) GetMethodID() uint32 {
	return AddRegistryID
}

// GetMethodSelector returns the function selector
func (t AddRegistryCall) GetMethodSelector() [4]byte {
	return AddRegistrySelector
}

// EncodeWithSelector encodes addRegistry arguments to ABI bytes including function selector
func (t AddRegistryCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], AddRegistrySelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewAddRegistryCall constructs a new AddRegistryCall
func NewAddRegistryCall(
	name string,
	description string,
	metadata string,
) *AddRegistryCall {
	return &AddRegistryCall{
		Name:        name,
		Description: description,
		Metadata:    metadata,
	}
}

const AddRegistryReturnStaticSize = 32

var _ abi.Tuple = (*AddRegistryReturn)(nil)
var _ abi.PackedTuple = (*AddRegistryReturn)(nil)

// AddRegistryReturn represents an ABI tuple
type AddRegistryReturn struct {
	RegistryId uint64
}

// EncodedSize returns the total encoded size of AddRegistryReturn
func (t AddRegistryReturn) EncodedSize() int {
	dynamicSize := 0

	return AddRegistryReturnStaticSize + dynamicSize
}

// EncodeTo encodes AddRegistryReturn to ABI bytes in the provided buffer
func (value AddRegistryReturn) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := AddRegistryReturnStaticSize // Start dynamic data after static section
	// Field RegistryId: uint64
	if _, err := abi.EncodeUint64(value.RegistryId, buf[0:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes AddRegistryReturn to ABI bytes
func (value AddRegistryReturn) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes AddRegistryReturn from ABI bytes in the provided buffer
func (t *AddRegistryReturn) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 32
	// Decode static field RegistryId: uint64
	t.RegistryId, _, err = abi.DecodeUint64(data[0:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

// PackedEncodedSize returns the packed encoded size of AddRegistryReturn
func (t AddRegistryReturn) PackedEncodedSize() int {
	return 8
}

// PackedEncodeTo encodes AddRegistryReturn to packed ABI bytes in the provided buffer
func (value AddRegistryReturn) PackedEncodeTo(buf []byte) (int, error) {
	// Encode tuple fields sequentially (packed, no dynamic section)
	var (
		offset int
		n      int
		err    error
	)
	// Field RegistryId: uint64
	n, err = abi.PackedEncodeUint64(value.RegistryId, buf[offset:])
	if err != nil {
		return 0, err
	}
	offset += n

	return offset, nil
}

// PackedEncode encodes AddRegistryReturn to packed ABI bytes
func (value AddRegistryReturn) PackedEncode() ([]byte, error) {
	buf := make([]byte, value.PackedEncodedSize())
	if _, err := value.PackedEncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// PackedDecode decodes AddRegistryReturn from packed ABI bytes
func (t *AddRegistryReturn) PackedDecode(data []byte) (int, error) {
	if len(data) < 8 {
		return 0, io.ErrUnexpectedEOF
	}
	var err error
	// Decode field RegistryId: uint64
	t.RegistryId, _, err = abi.PackedDecodeUint64(data[0:])
	if err != nil {
		return 0, err
	}
	return 8, nil
}

var _ abi.Method = (*GrantRoleCall)(nil)

const GrantRoleCallStaticSize = 128

var _ abi.Tuple = (*GrantRoleCall)(nil)

// GrantRoleCall represents an ABI tuple
type GrantRoleCall struct {
	RegistryId uint64
	Checksum   string
	Account    common.Address
	Role       string
}

// EncodedSize returns the total encoded size of GrantRoleCall
func (t GrantRoleCall) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += abi.SizeString(t.Checksum)
	dynamicSize += abi.SizeString(t.Role)

	return GrantRoleCallStaticSize + dynamicSize
}

// EncodeTo encodes GrantRoleCall to ABI bytes in the provided buffer
func (value GrantRoleCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := GrantRoleCallStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field RegistryId: uint64
	if _, err := abi.EncodeUint64(value.RegistryId, buf[0:]); err != nil {
		return 0, err
	}

	// Field Checksum: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Checksum, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field Account: address
	if _, err := abi.EncodeAddress(value.Account, buf[64:]); err != nil {
		return 0, err
	}

	// Field Role: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[96+24:96+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Role, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	return dynamicOffset, nil
}

// Encode encodes GrantRoleCall to ABI bytes
func (value GrantRoleCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes GrantRoleCall from ABI bytes in the provided buffer
func (t *GrantRoleCall) Decode(data []byte) (int, error) {
	if len(data) < 128 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err    error
		n      int
		offset int
	)
	dynamicOffset := 128
	// Decode static field RegistryId: uint64
	t.RegistryId, _, err = abi.DecodeUint64(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode dynamic field Checksum
	{
		offset, err = abi.DecodeSize(data[32:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.Checksum, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode static field Account: address
	t.Account, _, err = abi.DecodeAddress(data[64:])
	if err != nil {
		return 0, err
	}
	// Decode dynamic field Role
	{
		offset, err = abi.DecodeSize(data[96:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.Role, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	return dynamicOffset, nil
}

// GetMethodName returns the function name
func (t GrantRoleCall) GetMethodName() string {
	return "grantRole"
}

// GetMethodID returns the function id
func (t GrantRoleCall) GetMethodID() uint32 {
	return GrantRoleID
}

// GetMethodSelector returns the function selector
func (t GrantRoleCall) GetMethodSelector() [4]byte {
	return GrantRoleSelector
}

// EncodeWithSelector encodes grantRole arguments to ABI bytes including function selector
func (t GrantRoleCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], GrantRoleSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewGrantRoleCall constructs a new GrantRoleCall
func NewGrantRoleCall(
	registryId uint64,
	checksum string,
	account common.Address,
	role string,
) *GrantRoleCall {
	return &GrantRoleCall{
		RegistryId: registryId,
		Checksum:   checksum,
		Account:    account,
		Role:       role,
	}
}

// GrantRoleReturn represents the output arguments for grantRole function
type GrantRoleReturn struct {
	abi.EmptyTuple
}

var _ abi.Method = (*RecordsCall)(nil)

const RecordsCallStaticSize = 160

var _ abi.Tuple = (*RecordsCall)(nil)

// RecordsCall represents an ABI tuple
type RecordsCall struct {
	RegistryId uint64
	Checksum   string
	RecordId   uint64
	Index      uint64
	Pagination cmn.PageRequest
}

// EncodedSize returns the total encoded size of RecordsCall
func (t RecordsCall) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += abi.SizeString(t.Checksum)
	dynamicSize += t.Pagination.EncodedSize()

	return RecordsCallStaticSize + dynamicSize
}

// EncodeTo encodes RecordsCall to ABI bytes in the provided buffer
func (value RecordsCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := RecordsCallStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field RegistryId: uint64
	if _, err := abi.EncodeUint64(value.RegistryId, buf[0:]); err != nil {
		return 0, err
	}

	// Field Checksum: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Checksum, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field RecordId: uint64
	if _, err := abi.EncodeUint64(value.RecordId, buf[64:]); err != nil {
		return 0, err
	}

	// Field Index: uint64
	if _, err := abi.EncodeUint64(value.Index, buf[96:]); err != nil {
		return 0, err
	}

	// Field Pagination: (bytes,uint64,uint64,bool,bool)
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[128+24:128+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = value.Pagination.EncodeTo(buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	return dynamicOffset, nil
}

// Encode encodes RecordsCall to ABI bytes
func (value RecordsCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes RecordsCall from ABI bytes in the provided buffer
func (t *RecordsCall) Decode(data []byte) (int, error) {
	if len(data) < 160 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err    error
		n      int
		offset int
	)
	dynamicOffset := 160
	// Decode static field RegistryId: uint64
	t.RegistryId, _, err = abi.DecodeUint64(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode dynamic field Checksum
	{
		offset, err = abi.DecodeSize(data[32:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.Checksum, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode static field RecordId: uint64
	t.RecordId, _, err = abi.DecodeUint64(data[64:])
	if err != nil {
		return 0, err
	}
	// Decode static field Index: uint64
	t.Index, _, err = abi.DecodeUint64(data[96:])
	if err != nil {
		return 0, err
	}
	// Decode dynamic field Pagination
	{
		offset, err = abi.DecodeSize(data[128:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		n, err = t.Pagination.Decode(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	return dynamicOffset, nil
}

// GetMethodName returns the function name
func (t RecordsCall) GetMethodName() string {
	return "records"
}

// GetMethodID returns the function id
func (t RecordsCall) GetMethodID() uint32 {
	return RecordsID
}

// GetMethodSelector returns the function selector
func (t RecordsCall) GetMethodSelector() [4]byte {
	return RecordsSelector
}

// EncodeWithSelector encodes records arguments to ABI bytes including function selector
func (t RecordsCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], RecordsSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewRecordsCall constructs a new RecordsCall
func NewRecordsCall(
	registryId uint64,
	checksum string,
	recordId uint64,
	index uint64,
	pagination cmn.PageRequest,
) *RecordsCall {
	return &RecordsCall{
		RegistryId: registryId,
		Checksum:   checksum,
		RecordId:   recordId,
		Index:      index,
		Pagination: pagination,
	}
}

const RecordsReturnStaticSize = 64

var _ abi.Tuple = (*RecordsReturn)(nil)

// RecordsReturn represents an ABI tuple
type RecordsReturn struct {
	Records    []Record
	Pagination cmn.PageResponse
}

// EncodedSize returns the total encoded size of RecordsReturn
func (t RecordsReturn) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += SizeRecordSlice(t.Records)
	dynamicSize += t.Pagination.EncodedSize()

	return RecordsReturnStaticSize + dynamicSize
}

// EncodeTo encodes RecordsReturn to ABI bytes in the provided buffer
func (value RecordsReturn) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := RecordsReturnStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field Records: (string,string,string,string,string,string,uint64,uint64,bool,uint64)[]
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = EncodeRecordSlice(value.Records, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field Pagination: (bytes,uint64)
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = value.Pagination.EncodeTo(buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	return dynamicOffset, nil
}

// Encode encodes RecordsReturn to ABI bytes
func (value RecordsReturn) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes RecordsReturn from ABI bytes in the provided buffer
func (t *RecordsReturn) Decode(data []byte) (int, error) {
	if len(data) < 64 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err    error
		n      int
		offset int
	)
	dynamicOffset := 64
	// Decode dynamic field Records
	{
		offset, err = abi.DecodeSize(data[0:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.Records, n, err = DecodeRecordSlice(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode dynamic field Pagination
	{
		offset, err = abi.DecodeSize(data[32:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		n, err = t.Pagination.Decode(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	return dynamicOffset, nil
}

var _ abi.Method = (*RegistriesCall)(nil)

const RegistriesCallStaticSize = 64

var _ abi.Tuple = (*RegistriesCall)(nil)

// RegistriesCall represents an ABI tuple
type RegistriesCall struct {
	RegistryId uint64
	Pagination cmn.PageRequest
}

// EncodedSize returns the total encoded size of RegistriesCall
func (t RegistriesCall) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += t.Pagination.EncodedSize()

	return RegistriesCallStaticSize + dynamicSize
}

// EncodeTo encodes RegistriesCall to ABI bytes in the provided buffer
func (value RegistriesCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := RegistriesCallStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field RegistryId: uint64
	if _, err := abi.EncodeUint64(value.RegistryId, buf[0:]); err != nil {
		return 0, err
	}

	// Field Pagination: (bytes,uint64,uint64,bool,bool)
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = value.Pagination.EncodeTo(buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	return dynamicOffset, nil
}

// Encode encodes RegistriesCall to ABI bytes
func (value RegistriesCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes RegistriesCall from ABI bytes in the provided buffer
func (t *RegistriesCall) Decode(data []byte) (int, error) {
	if len(data) < 64 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err    error
		n      int
		offset int
	)
	dynamicOffset := 64
	// Decode static field RegistryId: uint64
	t.RegistryId, _, err = abi.DecodeUint64(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode dynamic field Pagination
	{
		offset, err = abi.DecodeSize(data[32:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		n, err = t.Pagination.Decode(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	return dynamicOffset, nil
}

// GetMethodName returns the function name
func (t RegistriesCall) GetMethodName() string {
	return "registries"
}

// GetMethodID returns the function id
func (t RegistriesCall) GetMethodID() uint32 {
	return RegistriesID
}

// GetMethodSelector returns the function selector
func (t RegistriesCall) GetMethodSelector() [4]byte {
	return RegistriesSelector
}

// EncodeWithSelector encodes registries arguments to ABI bytes including function selector
func (t RegistriesCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], RegistriesSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewRegistriesCall constructs a new RegistriesCall
func NewRegistriesCall(
	registryId uint64,
	pagination cmn.PageRequest,
) *RegistriesCall {
	return &RegistriesCall{
		RegistryId: registryId,
		Pagination: pagination,
	}
}

const RegistriesReturnStaticSize = 64

var _ abi.Tuple = (*RegistriesReturn)(nil)

// RegistriesReturn represents an ABI tuple
type RegistriesReturn struct {
	Registries []Registry
	Pagination cmn.PageResponse
}

// EncodedSize returns the total encoded size of RegistriesReturn
func (t RegistriesReturn) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += SizeRegistrySlice(t.Registries)
	dynamicSize += t.Pagination.EncodedSize()

	return RegistriesReturnStaticSize + dynamicSize
}

// EncodeTo encodes RegistriesReturn to ABI bytes in the provided buffer
func (value RegistriesReturn) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := RegistriesReturnStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field Registries: (uint64,string,string,string,string,string)[]
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = EncodeRegistrySlice(value.Registries, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field Pagination: (bytes,uint64)
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = value.Pagination.EncodeTo(buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	return dynamicOffset, nil
}

// Encode encodes RegistriesReturn to ABI bytes
func (value RegistriesReturn) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes RegistriesReturn from ABI bytes in the provided buffer
func (t *RegistriesReturn) Decode(data []byte) (int, error) {
	if len(data) < 64 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err    error
		n      int
		offset int
	)
	dynamicOffset := 64
	// Decode dynamic field Registries
	{
		offset, err = abi.DecodeSize(data[0:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.Registries, n, err = DecodeRegistrySlice(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode dynamic field Pagination
	{
		offset, err = abi.DecodeSize(data[32:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		n, err = t.Pagination.Decode(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	return dynamicOffset, nil
}

var _ abi.Method = (*RevokeRoleCall)(nil)

const RevokeRoleCallStaticSize = 128

var _ abi.Tuple = (*RevokeRoleCall)(nil)

// RevokeRoleCall represents an ABI tuple
type RevokeRoleCall struct {
	RegistryId uint64
	Checksum   string
	Account    common.Address
	Role       string
}

// EncodedSize returns the total encoded size of RevokeRoleCall
func (t RevokeRoleCall) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += abi.SizeString(t.Checksum)
	dynamicSize += abi.SizeString(t.Role)

	return RevokeRoleCallStaticSize + dynamicSize
}

// EncodeTo encodes RevokeRoleCall to ABI bytes in the provided buffer
func (value RevokeRoleCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := RevokeRoleCallStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field RegistryId: uint64
	if _, err := abi.EncodeUint64(value.RegistryId, buf[0:]); err != nil {
		return 0, err
	}

	// Field Checksum: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Checksum, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field Account: address
	if _, err := abi.EncodeAddress(value.Account, buf[64:]); err != nil {
		return 0, err
	}

	// Field Role: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[96+24:96+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Role, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	return dynamicOffset, nil
}

// Encode encodes RevokeRoleCall to ABI bytes
func (value RevokeRoleCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes RevokeRoleCall from ABI bytes in the provided buffer
func (t *RevokeRoleCall) Decode(data []byte) (int, error) {
	if len(data) < 128 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err    error
		n      int
		offset int
	)
	dynamicOffset := 128
	// Decode static field RegistryId: uint64
	t.RegistryId, _, err = abi.DecodeUint64(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode dynamic field Checksum
	{
		offset, err = abi.DecodeSize(data[32:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.Checksum, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode static field Account: address
	t.Account, _, err = abi.DecodeAddress(data[64:])
	if err != nil {
		return 0, err
	}
	// Decode dynamic field Role
	{
		offset, err = abi.DecodeSize(data[96:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.Role, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	return dynamicOffset, nil
}

// GetMethodName returns the function name
func (t RevokeRoleCall) GetMethodName() string {
	return "revokeRole"
}

// GetMethodID returns the function id
func (t RevokeRoleCall) GetMethodID() uint32 {
	return RevokeRoleID
}

// GetMethodSelector returns the function selector
func (t RevokeRoleCall) GetMethodSelector() [4]byte {
	return RevokeRoleSelector
}

// EncodeWithSelector encodes revokeRole arguments to ABI bytes including function selector
func (t RevokeRoleCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], RevokeRoleSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewRevokeRoleCall constructs a new RevokeRoleCall
func NewRevokeRoleCall(
	registryId uint64,
	checksum string,
	account common.Address,
	role string,
) *RevokeRoleCall {
	return &RevokeRoleCall{
		RegistryId: registryId,
		Checksum:   checksum,
		Account:    account,
		Role:       role,
	}
}

// RevokeRoleReturn represents the output arguments for revokeRole function
type RevokeRoleReturn struct {
	abi.EmptyTuple
}

var _ abi.Method = (*UpdateRecordStatusCall)(nil)

const UpdateRecordStatusCallStaticSize = 128

var _ abi.Tuple = (*UpdateRecordStatusCall)(nil)

// UpdateRecordStatusCall represents an ABI tuple
type UpdateRecordStatusCall struct {
	RegistryId uint64
	RecordId   uint64
	Index      uint64
	Status     string
}

// EncodedSize returns the total encoded size of UpdateRecordStatusCall
func (t UpdateRecordStatusCall) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += abi.SizeString(t.Status)

	return UpdateRecordStatusCallStaticSize + dynamicSize
}

// EncodeTo encodes UpdateRecordStatusCall to ABI bytes in the provided buffer
func (value UpdateRecordStatusCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := UpdateRecordStatusCallStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field RegistryId: uint64
	if _, err := abi.EncodeUint64(value.RegistryId, buf[0:]); err != nil {
		return 0, err
	}

	// Field RecordId: uint64
	if _, err := abi.EncodeUint64(value.RecordId, buf[32:]); err != nil {
		return 0, err
	}

	// Field Index: uint64
	if _, err := abi.EncodeUint64(value.Index, buf[64:]); err != nil {
		return 0, err
	}

	// Field Status: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[96+24:96+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Status, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	return dynamicOffset, nil
}

// Encode encodes UpdateRecordStatusCall to ABI bytes
func (value UpdateRecordStatusCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes UpdateRecordStatusCall from ABI bytes in the provided buffer
func (t *UpdateRecordStatusCall) Decode(data []byte) (int, error) {
	if len(data) < 128 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err    error
		n      int
		offset int
	)
	dynamicOffset := 128
	// Decode static field RegistryId: uint64
	t.RegistryId, _, err = abi.DecodeUint64(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode static field RecordId: uint64
	t.RecordId, _, err = abi.DecodeUint64(data[32:])
	if err != nil {
		return 0, err
	}
	// Decode static field Index: uint64
	t.Index, _, err = abi.DecodeUint64(data[64:])
	if err != nil {
		return 0, err
	}
	// Decode dynamic field Status
	{
		offset, err = abi.DecodeSize(data[96:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.Status, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	return dynamicOffset, nil
}

// GetMethodName returns the function name
func (t UpdateRecordStatusCall) GetMethodName() string {
	return "updateRecordStatus"
}

// GetMethodID returns the function id
func (t UpdateRecordStatusCall) GetMethodID() uint32 {
	return UpdateRecordStatusID
}

// GetMethodSelector returns the function selector
func (t UpdateRecordStatusCall) GetMethodSelector() [4]byte {
	return UpdateRecordStatusSelector
}

// EncodeWithSelector encodes updateRecordStatus arguments to ABI bytes including function selector
func (t UpdateRecordStatusCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], UpdateRecordStatusSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewUpdateRecordStatusCall constructs a new UpdateRecordStatusCall
func NewUpdateRecordStatusCall(
	registryId uint64,
	recordId uint64,
	index uint64,
	status string,
) *UpdateRecordStatusCall {
	return &UpdateRecordStatusCall{
		RegistryId: registryId,
		RecordId:   recordId,
		Index:      index,
		Status:     status,
	}
}

// UpdateRecordStatusReturn represents the output arguments for updateRecordStatus function
type UpdateRecordStatusReturn struct {
	abi.EmptyTuple
}

// Event signatures
var (
	// AddRecord(address,uint64,uint64,uint64,string)
	AddRecordEventTopic = common.Hash{0x1a, 0x32, 0x95, 0xfa, 0x8c, 0xc0, 0xe2, 0x8c, 0x95, 0xd2, 0x19, 0x12, 0xc9, 0xe6, 0x95, 0x8f, 0x3b, 0xc7, 0x40, 0x23, 0x17, 0x81, 0xf7, 0x64, 0x0a, 0xd8, 0x85, 0xc9, 0x72, 0xa3, 0x52, 0xfd}
	// AddRegistry(address,uint64,string)
	AddRegistryEventTopic = common.Hash{0x18, 0x17, 0x91, 0xbc, 0x37, 0x9a, 0xce, 0xdd, 0x36, 0x15, 0xcf, 0x06, 0x5d, 0x3c, 0x27, 0x5d, 0xfa, 0x6a, 0x3c, 0x46, 0x14, 0xc9, 0x06, 0x5d, 0x54, 0xc9, 0x87, 0x73, 0xf5, 0x76, 0x10, 0x8d}
	// GrantRole(address,uint64,string,address,string)
	GrantRoleEventTopic = common.Hash{0x0f, 0x49, 0xe3, 0x65, 0xba, 0xf9, 0x0d, 0xeb, 0x7d, 0x1f, 0x63, 0xe5, 0x76, 0x63, 0x79, 0x07, 0xe1, 0x2d, 0x1d, 0xdc, 0x75, 0xd1, 0xac, 0x68, 0x89, 0x4a, 0x2b, 0xcd, 0x19, 0x2b, 0x6d, 0xdb}
	// RevokeRole(address,uint64,string,address,string)
	RevokeRoleEventTopic = common.Hash{0x82, 0x36, 0xb7, 0x6c, 0xce, 0x80, 0xea, 0xf6, 0x9b, 0x54, 0xd8, 0x92, 0x68, 0xd0, 0x0f, 0xda, 0x3d, 0xec, 0x9e, 0x5e, 0x05, 0x4f, 0x15, 0x48, 0xeb, 0xbb, 0x1f, 0x8b, 0x20, 0xb3, 0xb0, 0x8b}
	// UpdateRecordStatus(address,uint64,uint64,uint64,string)
	UpdateRecordStatusEventTopic = common.Hash{0xd7, 0xb7, 0x54, 0x57, 0xd4, 0x12, 0x93, 0xea, 0xb4, 0x82, 0x99, 0x75, 0xc9, 0x51, 0xce, 0x8c, 0x53, 0x10, 0x68, 0x66, 0xf0, 0xc4, 0x29, 0xd1, 0x75, 0xfc, 0x6c, 0x91, 0xcd, 0xad, 0x5a, 0xde}
)

// AddRecordEvent represents the AddRecord event
var _ abi.Event = (*AddRecordEvent)(nil)

type AddRecordEvent struct {
	AddRecordEventIndexed
	AddRecordEventData
}

// NewAddRecordEvent constructs a new AddRecord event
func NewAddRecordEvent(
	caller common.Address,
	registryId uint64,
	recordId uint64,
	index uint64,
	checksum string,
) *AddRecordEvent {
	return &AddRecordEvent{
		AddRecordEventIndexed: AddRecordEventIndexed{
			Caller: caller,
		},
		AddRecordEventData: AddRecordEventData{
			RegistryId: registryId,
			RecordId:   recordId,
			Index:      index,
			Checksum:   checksum,
		},
	}
}

// GetEventName returns the event name
func (e AddRecordEvent) GetEventName() string {
	return "AddRecord"
}

// GetEventID returns the event ID (topic)
func (e AddRecordEvent) GetEventID() common.Hash {
	return AddRecordEventTopic
}

// AddRecord represents an ABI event
type AddRecordEventIndexed struct {
	Caller common.Address
}

// EncodeTopics encodes indexed fields of AddRecord event to topics
func (e AddRecordEventIndexed) EncodeTopics() ([]common.Hash, error) {
	topics := make([]common.Hash, 0, 2)
	topics = append(topics, AddRecordEventTopic)
	{
		// Caller
		var hash common.Hash
		if _, err := abi.EncodeAddress(e.Caller, hash[:]); err != nil {
			return nil, err
		}
		topics = append(topics, hash)
	}
	return topics, nil
}

// DecodeTopics decodes indexed fields of AddRecord event from topics, ignore hash topics
func (e *AddRecordEventIndexed) DecodeTopics(topics []common.Hash) error {
	if len(topics) != 2 {
		return abi.ErrInvalidNumberOfTopics
	}
	if topics[0] != AddRecordEventTopic {
		return abi.ErrInvalidEventTopic
	}
	var err error
	e.Caller, _, err = abi.DecodeAddress(topics[1][:])
	if err != nil {
		return err
	}
	return nil
}

const AddRecordEventDataStaticSize = 128

var _ abi.Tuple = (*AddRecordEventData)(nil)

// AddRecordEventData represents an ABI tuple
type AddRecordEventData struct {
	RegistryId uint64
	RecordId   uint64
	Index      uint64
	Checksum   string
}

// EncodedSize returns the total encoded size of AddRecordEventData
func (t AddRecordEventData) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += abi.SizeString(t.Checksum)

	return AddRecordEventDataStaticSize + dynamicSize
}

// EncodeTo encodes AddRecordEventData to ABI bytes in the provided buffer
func (value AddRecordEventData) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := AddRecordEventDataStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field RegistryId: uint64
	if _, err := abi.EncodeUint64(value.RegistryId, buf[0:]); err != nil {
		return 0, err
	}

	// Field RecordId: uint64
	if _, err := abi.EncodeUint64(value.RecordId, buf[32:]); err != nil {
		return 0, err
	}

	// Field Index: uint64
	if _, err := abi.EncodeUint64(value.Index, buf[64:]); err != nil {
		return 0, err
	}

	// Field Checksum: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[96+24:96+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Checksum, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	return dynamicOffset, nil
}

// Encode encodes AddRecordEventData to ABI bytes
func (value AddRecordEventData) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes AddRecordEventData from ABI bytes in the provided buffer
func (t *AddRecordEventData) Decode(data []byte) (int, error) {
	if len(data) < 128 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err    error
		n      int
		offset int
	)
	dynamicOffset := 128
	// Decode static field RegistryId: uint64
	t.RegistryId, _, err = abi.DecodeUint64(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode static field RecordId: uint64
	t.RecordId, _, err = abi.DecodeUint64(data[32:])
	if err != nil {
		return 0, err
	}
	// Decode static field Index: uint64
	t.Index, _, err = abi.DecodeUint64(data[64:])
	if err != nil {
		return 0, err
	}
	// Decode dynamic field Checksum
	{
		offset, err = abi.DecodeSize(data[96:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.Checksum, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	return dynamicOffset, nil
}

// AddRegistryEvent represents the AddRegistry event
var _ abi.Event = (*AddRegistryEvent)(nil)

type AddRegistryEvent struct {
	AddRegistryEventIndexed
	AddRegistryEventData
}

// NewAddRegistryEvent constructs a new AddRegistry event
func NewAddRegistryEvent(
	caller common.Address,
	registryId uint64,
	name string,
) *AddRegistryEvent {
	return &AddRegistryEvent{
		AddRegistryEventIndexed: AddRegistryEventIndexed{
			Caller: caller,
		},
		AddRegistryEventData: AddRegistryEventData{
			RegistryId: registryId,
			Name:       name,
		},
	}
}

// GetEventName returns the event name
func (e AddRegistryEvent) GetEventName() string {
	return "AddRegistry"
}

// GetEventID returns the event ID (topic)
func (e AddRegistryEvent) GetEventID() common.Hash {
	return AddRegistryEventTopic
}

// AddRegistry represents an ABI event
type AddRegistryEventIndexed struct {
	Caller common.Address
}

// EncodeTopics encodes indexed fields of AddRegistry event to topics
func (e AddRegistryEventIndexed) EncodeTopics() ([]common.Hash, error) {
	topics := make([]common.Hash, 0, 2)
	topics = append(topics, AddRegistryEventTopic)
	{
		// Caller
		var hash common.Hash
		if _, err := abi.EncodeAddress(e.Caller, hash[:]); err != nil {
			return nil, err
		}
		topics = append(topics, hash)
	}
	return topics, nil
}

// DecodeTopics decodes indexed fields of AddRegistry event from topics, ignore hash topics
func (e *AddRegistryEventIndexed) DecodeTopics(topics []common.Hash) error {
	if len(topics) != 2 {
		return abi.ErrInvalidNumberOfTopics
	}
	if topics[0] != AddRegistryEventTopic {
		return abi.ErrInvalidEventTopic
	}
	var err error
	e.Caller, _, err = abi.DecodeAddress(topics[1][:])
	if err != nil {
		return err
	}
	return nil
}

const AddRegistryEventDataStaticSize = 64

var _ abi.Tuple = (*AddRegistryEventData)(nil)

// AddRegistryEventData represents an ABI tuple
type AddRegistryEventData struct {
	RegistryId uint64
	Name       string
}

// EncodedSize returns the total encoded size of AddRegistryEventData
func (t AddRegistryEventData) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += abi.SizeString(t.Name)

	return AddRegistryEventDataStaticSize + dynamicSize
}

// EncodeTo encodes AddRegistryEventData to ABI bytes in the provided buffer
func (value AddRegistryEventData) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := AddRegistryEventDataStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field RegistryId: uint64
	if _, err := abi.EncodeUint64(value.RegistryId, buf[0:]); err != nil {
		return 0, err
	}

	// Field Name: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Name, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	return dynamicOffset, nil
}

// Encode encodes AddRegistryEventData to ABI bytes
func (value AddRegistryEventData) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes AddRegistryEventData from ABI bytes in the provided buffer
func (t *AddRegistryEventData) Decode(data []byte) (int, error) {
	if len(data) < 64 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err    error
		n      int
		offset int
	)
	dynamicOffset := 64
	// Decode static field RegistryId: uint64
	t.RegistryId, _, err = abi.DecodeUint64(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode dynamic field Name
	{
		offset, err = abi.DecodeSize(data[32:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.Name, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	return dynamicOffset, nil
}

// GrantRoleEvent represents the GrantRole event
var _ abi.Event = (*GrantRoleEvent)(nil)

type GrantRoleEvent struct {
	GrantRoleEventIndexed
	GrantRoleEventData
}

// NewGrantRoleEvent constructs a new GrantRole event
func NewGrantRoleEvent(
	caller common.Address,
	registryId uint64,
	checksum string,
	account common.Address,
	role string,
) *GrantRoleEvent {
	return &GrantRoleEvent{
		GrantRoleEventIndexed: GrantRoleEventIndexed{
			Caller: caller,
		},
		GrantRoleEventData: GrantRoleEventData{
			RegistryId: registryId,
			Checksum:   checksum,
			Account:    account,
			Role:       role,
		},
	}
}

// GetEventName returns the event name
func (e GrantRoleEvent) GetEventName() string {
	return "GrantRole"
}

// GetEventID returns the event ID (topic)
func (e GrantRoleEvent) GetEventID() common.Hash {
	return GrantRoleEventTopic
}

// GrantRole represents an ABI event
type GrantRoleEventIndexed struct {
	Caller common.Address
}

// EncodeTopics encodes indexed fields of GrantRole event to topics
func (e GrantRoleEventIndexed) EncodeTopics() ([]common.Hash, error) {
	topics := make([]common.Hash, 0, 2)
	topics = append(topics, GrantRoleEventTopic)
	{
		// Caller
		var hash common.Hash
		if _, err := abi.EncodeAddress(e.Caller, hash[:]); err != nil {
			return nil, err
		}
		topics = append(topics, hash)
	}
	return topics, nil
}

// DecodeTopics decodes indexed fields of GrantRole event from topics, ignore hash topics
func (e *GrantRoleEventIndexed) DecodeTopics(topics []common.Hash) error {
	if len(topics) != 2 {
		return abi.ErrInvalidNumberOfTopics
	}
	if topics[0] != GrantRoleEventTopic {
		return abi.ErrInvalidEventTopic
	}
	var err error
	e.Caller, _, err = abi.DecodeAddress(topics[1][:])
	if err != nil {
		return err
	}
	return nil
}

const GrantRoleEventDataStaticSize = 128

var _ abi.Tuple = (*GrantRoleEventData)(nil)

// GrantRoleEventData represents an ABI tuple
type GrantRoleEventData struct {
	RegistryId uint64
	Checksum   string
	Account    common.Address
	Role       string
}

// EncodedSize returns the total encoded size of GrantRoleEventData
func (t GrantRoleEventData) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += abi.SizeString(t.Checksum)
	dynamicSize += abi.SizeString(t.Role)

	return GrantRoleEventDataStaticSize + dynamicSize
}

// EncodeTo encodes GrantRoleEventData to ABI bytes in the provided buffer
func (value GrantRoleEventData) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := GrantRoleEventDataStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field RegistryId: uint64
	if _, err := abi.EncodeUint64(value.RegistryId, buf[0:]); err != nil {
		return 0, err
	}

	// Field Checksum: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Checksum, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field Account: address
	if _, err := abi.EncodeAddress(value.Account, buf[64:]); err != nil {
		return 0, err
	}

	// Field Role: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[96+24:96+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Role, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	return dynamicOffset, nil
}

// Encode encodes GrantRoleEventData to ABI bytes
func (value GrantRoleEventData) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes GrantRoleEventData from ABI bytes in the provided buffer
func (t *GrantRoleEventData) Decode(data []byte) (int, error) {
	if len(data) < 128 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err    error
		n      int
		offset int
	)
	dynamicOffset := 128
	// Decode static field RegistryId: uint64
	t.RegistryId, _, err = abi.DecodeUint64(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode dynamic field Checksum
	{
		offset, err = abi.DecodeSize(data[32:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.Checksum, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode static field Account: address
	t.Account, _, err = abi.DecodeAddress(data[64:])
	if err != nil {
		return 0, err
	}
	// Decode dynamic field Role
	{
		offset, err = abi.DecodeSize(data[96:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.Role, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	return dynamicOffset, nil
}

// RevokeRoleEvent represents the RevokeRole event
var _ abi.Event = (*RevokeRoleEvent)(nil)

type RevokeRoleEvent struct {
	RevokeRoleEventIndexed
	RevokeRoleEventData
}

// NewRevokeRoleEvent constructs a new RevokeRole event
func NewRevokeRoleEvent(
	caller common.Address,
	registryId uint64,
	checksum string,
	account common.Address,
	role string,
) *RevokeRoleEvent {
	return &RevokeRoleEvent{
		RevokeRoleEventIndexed: RevokeRoleEventIndexed{
			Caller: caller,
		},
		RevokeRoleEventData: RevokeRoleEventData{
			RegistryId: registryId,
			Checksum:   checksum,
			Account:    account,
			Role:       role,
		},
	}
}

// GetEventName returns the event name
func (e RevokeRoleEvent) GetEventName() string {
	return "RevokeRole"
}

// GetEventID returns the event ID (topic)
func (e RevokeRoleEvent) GetEventID() common.Hash {
	return RevokeRoleEventTopic
}

// RevokeRole represents an ABI event
type RevokeRoleEventIndexed struct {
	Caller common.Address
}

// EncodeTopics encodes indexed fields of RevokeRole event to topics
func (e RevokeRoleEventIndexed) EncodeTopics() ([]common.Hash, error) {
	topics := make([]common.Hash, 0, 2)
	topics = append(topics, RevokeRoleEventTopic)
	{
		// Caller
		var hash common.Hash
		if _, err := abi.EncodeAddress(e.Caller, hash[:]); err != nil {
			return nil, err
		}
		topics = append(topics, hash)
	}
	return topics, nil
}

// DecodeTopics decodes indexed fields of RevokeRole event from topics, ignore hash topics
func (e *RevokeRoleEventIndexed) DecodeTopics(topics []common.Hash) error {
	if len(topics) != 2 {
		return abi.ErrInvalidNumberOfTopics
	}
	if topics[0] != RevokeRoleEventTopic {
		return abi.ErrInvalidEventTopic
	}
	var err error
	e.Caller, _, err = abi.DecodeAddress(topics[1][:])
	if err != nil {
		return err
	}
	return nil
}

const RevokeRoleEventDataStaticSize = 128

var _ abi.Tuple = (*RevokeRoleEventData)(nil)

// RevokeRoleEventData represents an ABI tuple
type RevokeRoleEventData struct {
	RegistryId uint64
	Checksum   string
	Account    common.Address
	Role       string
}

// EncodedSize returns the total encoded size of RevokeRoleEventData
func (t RevokeRoleEventData) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += abi.SizeString(t.Checksum)
	dynamicSize += abi.SizeString(t.Role)

	return RevokeRoleEventDataStaticSize + dynamicSize
}

// EncodeTo encodes RevokeRoleEventData to ABI bytes in the provided buffer
func (value RevokeRoleEventData) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := RevokeRoleEventDataStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field RegistryId: uint64
	if _, err := abi.EncodeUint64(value.RegistryId, buf[0:]); err != nil {
		return 0, err
	}

	// Field Checksum: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Checksum, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field Account: address
	if _, err := abi.EncodeAddress(value.Account, buf[64:]); err != nil {
		return 0, err
	}

	// Field Role: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[96+24:96+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Role, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	return dynamicOffset, nil
}

// Encode encodes RevokeRoleEventData to ABI bytes
func (value RevokeRoleEventData) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes RevokeRoleEventData from ABI bytes in the provided buffer
func (t *RevokeRoleEventData) Decode(data []byte) (int, error) {
	if len(data) < 128 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err    error
		n      int
		offset int
	)
	dynamicOffset := 128
	// Decode static field RegistryId: uint64
	t.RegistryId, _, err = abi.DecodeUint64(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode dynamic field Checksum
	{
		offset, err = abi.DecodeSize(data[32:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.Checksum, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode static field Account: address
	t.Account, _, err = abi.DecodeAddress(data[64:])
	if err != nil {
		return 0, err
	}
	// Decode dynamic field Role
	{
		offset, err = abi.DecodeSize(data[96:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.Role, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	return dynamicOffset, nil
}

// UpdateRecordStatusEvent represents the UpdateRecordStatus event
var _ abi.Event = (*UpdateRecordStatusEvent)(nil)

type UpdateRecordStatusEvent struct {
	UpdateRecordStatusEventIndexed
	UpdateRecordStatusEventData
}

// NewUpdateRecordStatusEvent constructs a new UpdateRecordStatus event
func NewUpdateRecordStatusEvent(
	caller common.Address,
	registryId uint64,
	recordId uint64,
	index uint64,
	status string,
) *UpdateRecordStatusEvent {
	return &UpdateRecordStatusEvent{
		UpdateRecordStatusEventIndexed: UpdateRecordStatusEventIndexed{
			Caller: caller,
		},
		UpdateRecordStatusEventData: UpdateRecordStatusEventData{
			RegistryId: registryId,
			RecordId:   recordId,
			Index:      index,
			Status:     status,
		},
	}
}

// GetEventName returns the event name
func (e UpdateRecordStatusEvent) GetEventName() string {
	return "UpdateRecordStatus"
}

// GetEventID returns the event ID (topic)
func (e UpdateRecordStatusEvent) GetEventID() common.Hash {
	return UpdateRecordStatusEventTopic
}

// UpdateRecordStatus represents an ABI event
type UpdateRecordStatusEventIndexed struct {
	Caller common.Address
}

// EncodeTopics encodes indexed fields of UpdateRecordStatus event to topics
func (e UpdateRecordStatusEventIndexed) EncodeTopics() ([]common.Hash, error) {
	topics := make([]common.Hash, 0, 2)
	topics = append(topics, UpdateRecordStatusEventTopic)
	{
		// Caller
		var hash common.Hash
		if _, err := abi.EncodeAddress(e.Caller, hash[:]); err != nil {
			return nil, err
		}
		topics = append(topics, hash)
	}
	return topics, nil
}

// DecodeTopics decodes indexed fields of UpdateRecordStatus event from topics, ignore hash topics
func (e *UpdateRecordStatusEventIndexed) DecodeTopics(topics []common.Hash) error {
	if len(topics) != 2 {
		return abi.ErrInvalidNumberOfTopics
	}
	if topics[0] != UpdateRecordStatusEventTopic {
		return abi.ErrInvalidEventTopic
	}
	var err error
	e.Caller, _, err = abi.DecodeAddress(topics[1][:])
	if err != nil {
		return err
	}
	return nil
}

const UpdateRecordStatusEventDataStaticSize = 128

var _ abi.Tuple = (*UpdateRecordStatusEventData)(nil)

// UpdateRecordStatusEventData represents an ABI tuple
type UpdateRecordStatusEventData struct {
	RegistryId uint64
	RecordId   uint64
	Index      uint64
	Status     string
}

// EncodedSize returns the total encoded size of UpdateRecordStatusEventData
func (t UpdateRecordStatusEventData) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += abi.SizeString(t.Status)

	return UpdateRecordStatusEventDataStaticSize + dynamicSize
}

// EncodeTo encodes UpdateRecordStatusEventData to ABI bytes in the provided buffer
func (value UpdateRecordStatusEventData) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := UpdateRecordStatusEventDataStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field RegistryId: uint64
	if _, err := abi.EncodeUint64(value.RegistryId, buf[0:]); err != nil {
		return 0, err
	}

	// Field RecordId: uint64
	if _, err := abi.EncodeUint64(value.RecordId, buf[32:]); err != nil {
		return 0, err
	}

	// Field Index: uint64
	if _, err := abi.EncodeUint64(value.Index, buf[64:]); err != nil {
		return 0, err
	}

	// Field Status: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[96+24:96+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Status, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	return dynamicOffset, nil
}

// Encode encodes UpdateRecordStatusEventData to ABI bytes
func (value UpdateRecordStatusEventData) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes UpdateRecordStatusEventData from ABI bytes in the provided buffer
func (t *UpdateRecordStatusEventData) Decode(data []byte) (int, error) {
	if len(data) < 128 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err    error
		n      int
		offset int
	)
	dynamicOffset := 128
	// Decode static field RegistryId: uint64
	t.RegistryId, _, err = abi.DecodeUint64(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode static field RecordId: uint64
	t.RecordId, _, err = abi.DecodeUint64(data[32:])
	if err != nil {
		return 0, err
	}
	// Decode static field Index: uint64
	t.Index, _, err = abi.DecodeUint64(data[64:])
	if err != nil {
		return 0, err
	}
	// Decode dynamic field Status
	{
		offset, err = abi.DecodeSize(data[96:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.Status, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	return dynamicOffset, nil
}
