// Code generated by go-abi. DO NOT EDIT.

package precompile

import (
	"encoding/binary"
	"io"

	cmn "github.com/MANTRA-Chain/inveniam/precompiles"
	"github.com/yihuang/go-abi"
)

// Function selectors
var (
	// addDocument((string,string,string,string,string,string,string,string))
	AddDocumentSelector = [4]byte{0xa6, 0xf4, 0x09, 0x73}
	// documents(string,uint64,(bytes,uint64,uint64,bool,bool))
	DocumentsSelector = [4]byte{0xbd, 0x75, 0x92, 0x5a}
	// removeDocument(string,uint64)
	RemoveDocumentSelector = [4]byte{0x12, 0x0a, 0x43, 0xa9}
)

// Big endian integer versions of function selectors
const (
	AddDocumentID    = 2801011059
	DocumentsID      = 3178599002
	RemoveDocumentID = 302662569
)

const DocumentStaticSize = 256

var _ abi.Tuple = (*Document)(nil)

// Document represents an ABI tuple
type Document struct {
	Name         string
	Denom        string
	Uri          string
	Checksum     string
	ChecksumAlgo string
	Timestamp    string
	Figi         string
	IndividualId string
}

// EncodedSize returns the total encoded size of Document
func (t Document) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += abi.SizeString(t.Name)
	dynamicSize += abi.SizeString(t.Denom)
	dynamicSize += abi.SizeString(t.Uri)
	dynamicSize += abi.SizeString(t.Checksum)
	dynamicSize += abi.SizeString(t.ChecksumAlgo)
	dynamicSize += abi.SizeString(t.Timestamp)
	dynamicSize += abi.SizeString(t.Figi)
	dynamicSize += abi.SizeString(t.IndividualId)

	return DocumentStaticSize + dynamicSize
}

// EncodeTo encodes Document to ABI bytes in the provided buffer
func (value Document) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := DocumentStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field Name: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Name, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field Denom: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Denom, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field Uri: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[64+24:64+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Uri, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field Checksum: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[96+24:96+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Checksum, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field ChecksumAlgo: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[128+24:128+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.ChecksumAlgo, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field Timestamp: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[160+24:160+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Timestamp, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field Figi: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[192+24:192+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Figi, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field IndividualId: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[224+24:224+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.IndividualId, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	return dynamicOffset, nil
}

// Encode encodes Document to ABI bytes
func (value Document) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes Document from ABI bytes in the provided buffer
func (t *Document) Decode(data []byte) (int, error) {
	if len(data) < 256 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err    error
		n      int
		offset int
	)
	dynamicOffset := 256
	// Decode dynamic field Name
	{
		offset, err = abi.DecodeSize(data[0:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.Name, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode dynamic field Denom
	{
		offset, err = abi.DecodeSize(data[32:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.Denom, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode dynamic field Uri
	{
		offset, err = abi.DecodeSize(data[64:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.Uri, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode dynamic field Checksum
	{
		offset, err = abi.DecodeSize(data[96:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.Checksum, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode dynamic field ChecksumAlgo
	{
		offset, err = abi.DecodeSize(data[128:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.ChecksumAlgo, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode dynamic field Timestamp
	{
		offset, err = abi.DecodeSize(data[160:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.Timestamp, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode dynamic field Figi
	{
		offset, err = abi.DecodeSize(data[192:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.Figi, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode dynamic field IndividualId
	{
		offset, err = abi.DecodeSize(data[224:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.IndividualId, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	return dynamicOffset, nil
}

// EncodeDocumentSlice encodes (string,string,string,string,string,string,string,string)[] to ABI bytes
func EncodeDocumentSlice(value []Document, buf []byte) (int, error) {
	// Encode length
	binary.BigEndian.PutUint64(buf[24:32], uint64(len(value)))
	buf = buf[32:]

	// Encode elements with dynamic types
	var offset int
	dynamicOffset := len(value) * 32
	for _, elem := range value {
		// Write offset for element
		offset += 32
		binary.BigEndian.PutUint64(buf[offset-8:offset], uint64(dynamicOffset))

		// Write element at dynamic region
		n, err := elem.EncodeTo(buf[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}

	return dynamicOffset + 32, nil
}

// SizeDocumentSlice returns the encoded size of (string,string,string,string,string,string,string,string)[]
func SizeDocumentSlice(value []Document) int {
	size := 32 + 32*len(value) // length + offset pointers for dynamic elements
	for _, elem := range value {
		size += elem.EncodedSize()
	}
	return size
}

// DecodeDocumentSlice decodes (string,string,string,string,string,string,string,string)[] from ABI bytes
func DecodeDocumentSlice(data []byte) ([]Document, int, error) {
	// Decode length
	if len(data) < 32 {
		return nil, 0, io.ErrUnexpectedEOF
	}
	length, err := abi.DecodeSize(data)
	if err != nil {
		return nil, 0, err
	}
	data = data[32:]
	if length > len(data) || length*32 > len(data) {
		return nil, 0, io.ErrUnexpectedEOF
	}
	var (
		n      int
		offset int
	)
	// Decode elements with dynamic types
	result := make([]Document, length)
	dynamicOffset := length * 32
	for i := 0; i < length; i++ {
		tmp, err := abi.DecodeSize(data[offset:])
		if err != nil {
			return nil, 0, err
		}
		offset += 32

		if dynamicOffset != tmp {
			return nil, 0, abi.ErrInvalidOffsetForSliceElement
		}
		n, err = result[i].Decode(data[dynamicOffset:])
		if err != nil {
			return nil, 0, err
		}
		dynamicOffset += n
	}
	return result, dynamicOffset + 32, nil
}

var _ abi.Method = (*AddDocumentCall)(nil)

const AddDocumentCallStaticSize = 32

var _ abi.Tuple = (*AddDocumentCall)(nil)

// AddDocumentCall represents an ABI tuple
type AddDocumentCall struct {
	Document Document
}

// EncodedSize returns the total encoded size of AddDocumentCall
func (t AddDocumentCall) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += t.Document.EncodedSize()

	return AddDocumentCallStaticSize + dynamicSize
}

// EncodeTo encodes AddDocumentCall to ABI bytes in the provided buffer
func (value AddDocumentCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := AddDocumentCallStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field Document: (string,string,string,string,string,string,string,string)
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = value.Document.EncodeTo(buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	return dynamicOffset, nil
}

// Encode encodes AddDocumentCall to ABI bytes
func (value AddDocumentCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes AddDocumentCall from ABI bytes in the provided buffer
func (t *AddDocumentCall) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err    error
		n      int
		offset int
	)
	dynamicOffset := 32
	// Decode dynamic field Document
	{
		offset, err = abi.DecodeSize(data[0:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		n, err = t.Document.Decode(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	return dynamicOffset, nil
}

// GetMethodName returns the function name
func (t AddDocumentCall) GetMethodName() string {
	return "addDocument"
}

// GetMethodID returns the function id
func (t AddDocumentCall) GetMethodID() uint32 {
	return AddDocumentID
}

// GetMethodSelector returns the function selector
func (t AddDocumentCall) GetMethodSelector() [4]byte {
	return AddDocumentSelector
}

// EncodeWithSelector encodes addDocument arguments to ABI bytes including function selector
func (t AddDocumentCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], AddDocumentSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewAddDocumentCall constructs a new AddDocumentCall
func NewAddDocumentCall(
	document Document,
) *AddDocumentCall {
	return &AddDocumentCall{
		Document: document,
	}
}

// AddDocumentReturn represents the output arguments for addDocument function
type AddDocumentReturn struct {
	abi.EmptyTuple
}

var _ abi.Method = (*DocumentsCall)(nil)

const DocumentsCallStaticSize = 96

var _ abi.Tuple = (*DocumentsCall)(nil)

// DocumentsCall represents an ABI tuple
type DocumentsCall struct {
	Denom      string
	Index      uint64
	Pagination cmn.PageRequest
}

// EncodedSize returns the total encoded size of DocumentsCall
func (t DocumentsCall) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += abi.SizeString(t.Denom)
	dynamicSize += t.Pagination.EncodedSize()

	return DocumentsCallStaticSize + dynamicSize
}

// EncodeTo encodes DocumentsCall to ABI bytes in the provided buffer
func (value DocumentsCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := DocumentsCallStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field Denom: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Denom, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field Index: uint64
	if _, err := abi.EncodeUint64(value.Index, buf[32:]); err != nil {
		return 0, err
	}

	// Field Pagination: (bytes,uint64,uint64,bool,bool)
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[64+24:64+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = value.Pagination.EncodeTo(buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	return dynamicOffset, nil
}

// Encode encodes DocumentsCall to ABI bytes
func (value DocumentsCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes DocumentsCall from ABI bytes in the provided buffer
func (t *DocumentsCall) Decode(data []byte) (int, error) {
	if len(data) < 96 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err    error
		n      int
		offset int
	)
	dynamicOffset := 96
	// Decode dynamic field Denom
	{
		offset, err = abi.DecodeSize(data[0:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.Denom, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode static field Index: uint64
	t.Index, _, err = abi.DecodeUint64(data[32:])
	if err != nil {
		return 0, err
	}
	// Decode dynamic field Pagination
	{
		offset, err = abi.DecodeSize(data[64:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		n, err = t.Pagination.Decode(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	return dynamicOffset, nil
}

// GetMethodName returns the function name
func (t DocumentsCall) GetMethodName() string {
	return "documents"
}

// GetMethodID returns the function id
func (t DocumentsCall) GetMethodID() uint32 {
	return DocumentsID
}

// GetMethodSelector returns the function selector
func (t DocumentsCall) GetMethodSelector() [4]byte {
	return DocumentsSelector
}

// EncodeWithSelector encodes documents arguments to ABI bytes including function selector
func (t DocumentsCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], DocumentsSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewDocumentsCall constructs a new DocumentsCall
func NewDocumentsCall(
	denom string,
	index uint64,
	pagination cmn.PageRequest,
) *DocumentsCall {
	return &DocumentsCall{
		Denom:      denom,
		Index:      index,
		Pagination: pagination,
	}
}

const DocumentsReturnStaticSize = 64

var _ abi.Tuple = (*DocumentsReturn)(nil)

// DocumentsReturn represents an ABI tuple
type DocumentsReturn struct {
	Documents  []Document
	Pagination cmn.PageResponse
}

// EncodedSize returns the total encoded size of DocumentsReturn
func (t DocumentsReturn) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += SizeDocumentSlice(t.Documents)
	dynamicSize += t.Pagination.EncodedSize()

	return DocumentsReturnStaticSize + dynamicSize
}

// EncodeTo encodes DocumentsReturn to ABI bytes in the provided buffer
func (value DocumentsReturn) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := DocumentsReturnStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field Documents: (string,string,string,string,string,string,string,string)[]
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = EncodeDocumentSlice(value.Documents, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field Pagination: (bytes,uint64)
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = value.Pagination.EncodeTo(buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	return dynamicOffset, nil
}

// Encode encodes DocumentsReturn to ABI bytes
func (value DocumentsReturn) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes DocumentsReturn from ABI bytes in the provided buffer
func (t *DocumentsReturn) Decode(data []byte) (int, error) {
	if len(data) < 64 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err    error
		n      int
		offset int
	)
	dynamicOffset := 64
	// Decode dynamic field Documents
	{
		offset, err = abi.DecodeSize(data[0:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.Documents, n, err = DecodeDocumentSlice(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode dynamic field Pagination
	{
		offset, err = abi.DecodeSize(data[32:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		n, err = t.Pagination.Decode(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	return dynamicOffset, nil
}

var _ abi.Method = (*RemoveDocumentCall)(nil)

const RemoveDocumentCallStaticSize = 64

var _ abi.Tuple = (*RemoveDocumentCall)(nil)

// RemoveDocumentCall represents an ABI tuple
type RemoveDocumentCall struct {
	Denom string
	Index uint64
}

// EncodedSize returns the total encoded size of RemoveDocumentCall
func (t RemoveDocumentCall) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += abi.SizeString(t.Denom)

	return RemoveDocumentCallStaticSize + dynamicSize
}

// EncodeTo encodes RemoveDocumentCall to ABI bytes in the provided buffer
func (value RemoveDocumentCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := RemoveDocumentCallStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field Denom: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Denom, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field Index: uint64
	if _, err := abi.EncodeUint64(value.Index, buf[32:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes RemoveDocumentCall to ABI bytes
func (value RemoveDocumentCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes RemoveDocumentCall from ABI bytes in the provided buffer
func (t *RemoveDocumentCall) Decode(data []byte) (int, error) {
	if len(data) < 64 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err    error
		n      int
		offset int
	)
	dynamicOffset := 64
	// Decode dynamic field Denom
	{
		offset, err = abi.DecodeSize(data[0:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.Denom, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode static field Index: uint64
	t.Index, _, err = abi.DecodeUint64(data[32:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

// GetMethodName returns the function name
func (t RemoveDocumentCall) GetMethodName() string {
	return "removeDocument"
}

// GetMethodID returns the function id
func (t RemoveDocumentCall) GetMethodID() uint32 {
	return RemoveDocumentID
}

// GetMethodSelector returns the function selector
func (t RemoveDocumentCall) GetMethodSelector() [4]byte {
	return RemoveDocumentSelector
}

// EncodeWithSelector encodes removeDocument arguments to ABI bytes including function selector
func (t RemoveDocumentCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], RemoveDocumentSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewRemoveDocumentCall constructs a new RemoveDocumentCall
func NewRemoveDocumentCall(
	denom string,
	index uint64,
) *RemoveDocumentCall {
	return &RemoveDocumentCall{
		Denom: denom,
		Index: index,
	}
}

// RemoveDocumentReturn represents the output arguments for removeDocument function
type RemoveDocumentReturn struct {
	abi.EmptyTuple
}
