syntax = "proto3";
package mantrachain.anchoring.v1;

import "amino/amino.proto";
import "cosmos/msg/v1/msg.proto";
import "cosmos_proto/cosmos.proto";
import "gogoproto/gogo.proto";
import "mantrachain/anchoring/v1/params.proto";
import "mantrachain/anchoring/v1/document.proto";

option go_package = "github.com/MANTRA-Chain/nvnmchain/x/anchoring/types";

// Msg defines the Msg service.
service Msg {
  option (cosmos.msg.v1.service) = true;

  // UpdateParams defines a (governance) operation for updating the module
  // parameters. The authority defaults to the x/gov module account.
  rpc UpdateParams(MsgUpdateParams) returns (MsgUpdateParamsResponse);

  // AddRegistry defines a method for adding a record registry
  rpc AddRegistry(MsgAddRegistry) returns (MsgAddRegistryResponse);

  // AddRecord defines a method for adding a record to a registry
  rpc AddRecord(MsgAddRecord) returns (MsgAddRecordResponse);

  // UpdateRecordStatus defines a method for updating the status of a record in
  // a registry
  rpc UpdateRecordStatus(MsgUpdateRecordStatus)
  returns (MsgUpdateRecordStatusResponse);

  // GrantRole defines a method for granting a role to an address
  rpc GrantRole(MsgGrantRole) returns (MsgGrantRoleResponse);

  // RevokeRole defines a method for revoking a role from an address
  rpc RevokeRole(MsgRevokeRole) returns (MsgRevokeRoleResponse);
}

// MsgUpdateParams is the Msg/UpdateParams request type.
message MsgUpdateParams {
  option (amino.name) = "nvnmchain/x/anchoring/MsgUpdateParams";
  option (cosmos.msg.v1.signer) = "authority";

  // authority is the address that controls the module parameters.
  string authority = 1 [ (cosmos_proto.scalar) = "cosmos.AddressString" ];
  string admin     = 2 [ (cosmos_proto.scalar) = "cosmos.AddressString" ];
}

// MsgUpdateParamsResponse defines the response structure for executing a
// MsgUpdateParams message.
message MsgUpdateParamsResponse {}

// MsgAddRegistry is the Msg/AddRegistry request type.
message MsgAddRegistry {
  option (amino.name) = "nvnmchain/x/anchoring/MsgAddRegistry";
  option (cosmos.msg.v1.signer) = "sender";
  // sender is the address that creates the registry.
  string sender = 1 [ (cosmos_proto.scalar) = "cosmos.AddressString" ];
  // name of the registry
  string name = 2;
  // description of the registry
  string description = 3;
  // metadata of the registry
  string metadata = 4;
}

// MsgAddRegistryResponse defines the response structure for executing a
// MsgAddRegistry message.
message MsgAddRegistryResponse {
  uint64 registry_id = 1;
}

// MsgAddRecord is the Msg/AddRecord request type.
message MsgAddRecord {
  option (amino.name) = "nvnmchain/x/anchoring/MsgAddRecord";
  option (cosmos.msg.v1.signer) = "sender";

  // sender is the address that sends the document addition request.
  string sender = 1 [ (cosmos_proto.scalar) = "cosmos.AddressString" ];
  Record record = 2;
}

// MsgAddRecordResponse defines the response structure for executing a
// MsgAddRecord message.
message MsgAddRecordResponse {
  uint64 record_id = 1;
}

// MsgUpdateRecordStatus is the Msg/UpdateRecordStatus request type.
message MsgUpdateRecordStatus {
  option (amino.name) = "nvnmchain/x/anchoring/MsgUpdateRecordStatus";
  option (cosmos.msg.v1.signer) = "editor";
  // editor is the address that updates the record status.
  string editor = 1 [ (cosmos_proto.scalar) = "cosmos.AddressString" ];
  // registry_id of the record
  uint64 registry_id = 2;
  // record_id of the record
  uint64 record_id = 3;
  // index of the record
  uint64 index = 4;
  // new status of the record
  string status = 5;
}

//  MsgUpdateRecordStatusResponse defines the response structure for executing a
//  MsgUpdateRecordStatus message.
message MsgUpdateRecordStatusResponse {}

// MsgGrantRole is the Msg/GrantRole request type.
message MsgGrantRole {
  option (amino.name) = "nvnmchain/x/anchoring/MsgGrantRole";
  option (cosmos.msg.v1.signer) = "admin";

  // admin is the address that grants the role.
  string admin = 1 [ (cosmos_proto.scalar) = "cosmos.AddressString" ];
  // address to grant role to
  string address = 2 [ (cosmos_proto.scalar) = "cosmos.AddressString" ];
  // registry_id
  uint64 registry_id = 3;
  // checksum of document
  string checksum = 4;
  // role to grant (e.g., "admin", "editor")
  string role = 5;
}

message MsgGrantRoleResponse {}

// MsgRevokeRole is the Msg/RevokeRole request type.
message MsgRevokeRole {
  option (amino.name) = "nvnmchain/x/anchoring/MsgRevokeRole";
  option (cosmos.msg.v1.signer) = "admin";

  // admin is the address that revokes the role.
  string admin = 1 [ (cosmos_proto.scalar) = "cosmos.AddressString" ];
  // address to revoke role from
  string address = 2 [ (cosmos_proto.scalar) = "cosmos.AddressString" ];
  // registry_id
  uint64 registry_id = 3;
  // checksum of document
  string checksum = 4;
  // role to revoke (e.g., "admin", "editor")
  string role = 5;
}

message MsgRevokeRoleResponse {}